### ISSUE TITLE
tap?

### ISSUE THREAD

**Issue by dweinstein** [caolan/highland#109]
It feels like _.tap is missing (map without the need to remember to return?)

**Comment by bolus** [comment]
An alias for 'doto' would be great. Often I don't change the object and in these cases 'tap' would make more sense.

Also: I was searching for a 'tap' method on the HL API page, couldn't find one and found this page via Google. There a probably other people, besides me and dweinstein, who search for 'tap' on the API page.

Btw., thanks a million for creating HL!

**Comment by StreetStrider** [comment]
`_.tap` is much more comprehensive.

**Comment by vqvu** [comment]
I'd support `tap` as an alias for `doto` to match other libraries.

@StreetStrider, what do you mean by "more comprehensive."

**Comment by LewisJEllis** [comment]
+1 `tap` aliasing `doto`

**Comment by vqvu** [comment]
Anybody want to write the (two lines of) code to do this? ;)

+1 tap aliasing doto

—
Reply to this email directly or view it on GitHub
<https://github.com/caolan/highland/issues/109#issuecomment-74604266>.

**Comment by StreetStrider** [comment]
@vqvu, I mean `tap` is simple and one-word name, instead `doto` is compound. `tap` means something that intercepts a transmission and do not change the message. `doto` sounds like «to do something to transmitted message» and much more looks like `map`.

I also prefer `tap`, because LoDash, for instance uses this name in it's chaining syntax in analogous role.

**Comment by quarterto** [comment]
@StreetStrider I think you meant "[comprehensible](http://en.wiktionary.org/wiki/comprehensible)" rather than "[comprehensive](http://en.wiktionary.org/wiki/comprehensive)"

**Comment by StreetStrider** [comment]
@quarterto, yes, that is my mistake, thanks for the tip.

**Comment by svozza** [comment]
Yep, +1 on this. While I can appreciate the logic of why it's named `doto` I think it would be better to be in line with the common naming convention of most libs.
