### ISSUE TITLE
highland eating errors

### ISSUE THREAD

**Issue by mpj** [caolan/highland#121]
Perhaps I'm using it in the wrong way, but I find highland to be notoriously difficult to work with due to it's tendency to swallow and keep error messages somewhere rather than throwing them. During development, it's really frustrating to make a syntax error somewhere, and it being eaten due to the fact that you've forgotten to add an error handler somewhere, making you flail around trying to find out where you've made the error. The output of the code below is just...

```
data: undefined
```

... which is just really weird and unhelpful. 

```javascript
var _ = require("highland");

var a = _();

var b = a.map(function(val) {
  throw new Error('I will make a mistake in this function')
})

b.on('data', function(data) {
  console.log("data:", data)
})

process.on('uncaughtException', function(err) {
  console.log('This will not trigger!');
});
 
try {
  a.write("something")
} catch(e) {
  console.log('This will not trigger!');
}
```

**Comment by ibash** [comment]
+1 on no silent errors
Another reason is that right now highland is inconsistent w.r.t how it treats errors. For example `pipe` and `toArray` throw the error if it's not handled whereas the example above does not.

**Comment by vqvu** [comment]
I think this is a bug somewhere in v2.x. You shouldn't get a `data` entry with `undefined` when you emit an error.

This doesn't happen in 3.0.0, so the fix is in there somewhere...

**Comment by vqvu** [comment]
Fixed. Errors are now emitted on to the correct handler when you have a `data` or `end` handler bound.

That said, i would not depend on these handlers. Use the highland API: `errors`, `each`, `toArray`, etc. You'll get much better results. A highland stream is not a node stream. It just provides some interop with node streams.
