### ISSUE TITLE
Problem with the new merge strategy

### ISSUE THREAD

**Issue by jeromew** [caolan/highland#132]
@caolan , 

before 2.0.0, the "merge" strategy was to pull from `self` (the streams containing the sub-streams) and pull from the sub-streams all in parallel.

so you could have a potentially infinite stream of short sub-streams.

now with the new strategy, we have a toArray() on the main stream; so we have to wait for the main stream to finish before anything can be read from the substreams.

It breaks my use case where I have a stream of tokens that generate sub-stream 'views' on this stream of tokens and I must pull from them all in parallel (if I pull everything from the mainstream, the substreams are already finished, or locked in their highWaterMark).

I am trying to find an alternative but is it a definitive choice that toArray is used to gather all the sources as a first step ?

**Comment by LewisJEllis** [comment]
@jeromew can this be closed now that #133 is merged?

**Comment by jeromew** [comment]
yep thanks
