### ISSUE TITLE
[question] Is this project still being maintained?

### ISSUE THREAD

**Issue by davidchase** [caolan/highland#144]

**Comment by quarterto** [comment]
I'd like to nominate @jgrund and @svozza for collaborator status. They've both been fairly active the last few weeks. @caolan

**Comment by vqvu** [comment]
@caolan I second this. @svozza especially has done quite a bit of work.

**Comment by caolan** [comment]
@quarterto @vqvu @jgrund @svozza +2 ;) thanks for all your hard work!

**Comment by svozza** [comment]
Thanks. :) We use Highland so much in work, it's the least I can do.
