### ISSUE TITLE
_. prefix in Functions section of docs

### ISSUE THREAD

**Issue by LewisJEllis** [caolan/highland#170]
I noticed that everything in the Functions section (and the example for `_.add`) neglects the `_.` prefix. It seems out of place with everything else being prefixed by either `_.` or `Stream.`; is there a reason for this?

**Comment by vqvu** [comment]
I don't see a real reason...probably just an oversight that never got fixed?

**Comment by jeromew** [comment]
I don't see a reason either. +1
