### ISSUE TITLE
Allow ratelimit to limit errors

### ISSUE THREAD

**Issue by jgrund** [caolan/highland#186]
I have a use case where I'd like errors to be limited the same way as values are by `ratelimit`.

I think it could make sense to pass an optional flag to `ratelimit` indicating whether we want to limit errors.

If this is agreeable, I'll send a PR.

**Comment by vqvu** [comment]
We want to avoid optional parameters in transforms because they can't be correctly curried, so this would have to be a new transform.

However, can't you just use `errors` to push the errors as some sort of special value and _then_ use `ratelimit`?

**Comment by jgrund** [comment]
Ah, right, forgot about the currying.

I could use `errors` to mutate the errors as values, but at that point I'm just transforming the data to match the implementation; which I'd rather not do.

Given I'm the first to comment on this, it probably doesn't merit another transform.

The internal implementation of `ratelimit` is quite simple. I'll just use `through` to create a transform that ratelimits errors as well.
