### ISSUE TITLE
Impact Of Arguments Arraylike Object On Performance

### ISSUE THREAD

**Issue by svozza** [caolan/highland#193]
I was having a read of the performance optimisations wiki on the Bluebird wiki and there was some interesting stuff about the use of `arguments`, which is quite prevalent in the Highland codebase:

https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments

Particularly this:

>There are numerous ways to use arguments in a way that causes the function to be unoptimizable. One must be extremely careful when using arguments.

>Only use

>  * arguments.length
> 
* arguments[i] where i is always a valid integer index into the arguments, and can not be out of bound
> 
* Never use arguments directly without .length or [i] (STRICTLY x.apply(y, arguments) is ok, nothing else is, e.g. .slice. Function#apply is special)

As an experiment, I went through the code and replaced all references to arguments with something equivalent to the workarounds listed on the wiki. I ran all the tests and the bench test too and found it made absolutely no difference to the performance of either. It also makes the code look incredibly ugly so it looks like the warning near the end of the wiki page applies in our case:

>It takes a lot of code and is annoying so it might be worth to analyze if it's really worth it.

**Comment by LewisJEllis** [comment]
Caolan doesn't seem to be worried about bleeding-edge performance (see #175), but highland's benchmarking is definitely something that can (and for 3.0.0, will most likely) be improved.

**Comment by vqvu** [comment]
I think `arguments` is mostly used in the functional composition parts of the library (`curry`, `partial`, etc). The critical paths don't use it.

I'm more concerned about section 3.2 in that Bluebird link about leaking arguments. Although again, it's not a big deal unless you routinely use `curry` and friends.

**Comment by svozza** [comment]
Yeah, `curry` is what I first thought of because every function in the library is curried and also exposeMethod uses `arguments` too. But I used something similar (actually pilfered from Lodash) to the workaround mentioned to prevent leaking `arguments` in all the functions I could find and as I said, it seemed like a waste of time and made the code really ugly. E.g.,

```javascript
if (mappingHintType === 'function') {
            mapper = mappingHint;
        } else if (mappingHintType === 'number') {
            mapper = function () {
                var length = arguments.length,
                    index = length,
                    args = new Array(length);
                while (index--) {
                    args[index] = arguments[index];
                }
                return args.slice(0, mappingHint);
            };
        } else if (_.isArray(mappingHint)) {
            mapper = function () {
                var length1 = arguments.length,
                    index1 = length1,
                    args1 = new Array(length1);
                while (index1--) {
                    args1[index1] = arguments[index1];
                }
                return mappingHint.reduce(function (ctx, hint, idx) {
                    ctx[hint] = args1[idx];
                    return ctx;
                }, {});
            };
        } else {
            mapper = function (x) { return x; };
        }

        ee.on(xs, function () {
            var length2 = arguments.length,
                index2 = length2,
                args2 = new Array(length2);
            while (index2--) {
                args2[index2] = arguments[index2];
            }
            var ctx = mapper.apply(this, args2);
            self.write(ctx);
        });
```
Of course maybe I'm just doing something wrong, it has been known to happen!

**Comment by quarterto** [comment]
Looks like most if not all of our usage of `arguments` could be replaced with ES6 rest parameters. I'm not suggesting we start transpiling now but maybe when ES6 gets widespread adoption we can port it.
