### ISSUE TITLE
Wrap streams inside objects

### ISSUE THREAD

**Issue by Marsup** [caolan/highland#194]
Hi,

I'm trying to create a stream based on an array of image urls that would create as many streams, add some meta information around it, and stream it.
So basically I want to transform
```js
['http://a/b.png', 'http://a/c.png']
```
to something like
```js
[{ name: 'b.png', content: '...' }, { name: 'c.png', content: '...' }]
```
where the content of the files would be in base64.

I've been trying the whole day, I don't see any way to achieve this with highland without buffering the whole file content.

Anyone with an idea ?

**Comment by quarterto** [comment]
As you've described it, highland or no, you're always going to have to buffer the contents if you want the full content as base64 in the object.

**Comment by Marsup** [comment]
While not very sexy, in a pure stream, I could emit `[` then `{ name: 'b.png', content:` followed by the content then `}` and continue until I have no more objects and emit the final `]`. Is there a way to somehow pipe a new stream to the current stream in `consume` which I think would be appropriate to recreate this behavior ? Maybe pushing a stream ?

**Comment by quarterto** [comment]
Oh, I thought you meant you wanted an array of objects, not a JSON stream. You can do what you want with `flatMap` and `concat`/`append`:

```javascript
_(['{']).concat(_(['http://a/b.png', 'http://a/c.png']).flatMap(function(url) {
  var name = path.basename(url);
  return _(['{name: "', name, '",]).concat(request(url)).append('}');
}).intersperse(',')).append(']');
```

There's probably a cleaner way of doing it with JSONStream.

Note that `consume` is really just meant as a low-level API; if you have to use `consume` in userland code, it probably means we're missing a method.

**Comment by Marsup** [comment]
I don't think JSONStream accepts streams as value so I'd also have to read the whole stream before.

Your solution is almost working, it seems request doesn't handle encoding when it's piped so I had to change it a bit.
My current code looks like this :
```js
_(['[']).concat(_(images).flatMap(function (url) {
  var image = _(request(url)).invoke('toString', ['base64']);
  return _(['{"name":"' + url + '","content":"']).concat(image).append('"}');
}).intersperse(',')).append(']').toArray(function (arr) {
  console.log(arr);
});
```
The weird thing is I get multiple chunks of the file separated by `,`, I don't understand why that is.
Also, the stream ends with `,` followed by `}`, it's probably going to cause a parser error.

**Comment by quarterto** [comment]
There must be a better way than manually constructing JSON strings. You can use `through` to transform Highland streams using Node transform streams:

```javascript
_(['http://a/b.png', 'http://a/c.png']).flatMap(function(url) {
  // something
}).through(JSONStream.stringify())
```

However, I'm not sure how exactly to I'd construct the objects.

**Comment by Marsup** [comment]
I've been trying again today, and made some progress, but I think it's impossible.

First, the way I did base64 was not good at all, `invoke` won't make it since the base64 of each chunk is not equivalent to that of the whole. My best bet on this is to use base64-stream which seems to be unmaintained. I think the equivalent in pure highland would be overly complicated and inefficient (split, batch by 3, join, toString in base64).

Now there's the problem that `intersperse` considers each chunk pushed by individual streams of the flatMap and doesn't wait for the end of each stream to insert the character, I guess it's the expected behavior since it doesn't have knowledge of multiple streams ?

As for JSONStream, it expects fully formed objects, it does a JSON.stringify of everything that's written to it, so that won't be possible.

**Comment by Marsup** [comment]
Actually I've just found a probably dirty way to do it. End my inner stream with `append('}\0')` then splitBy '\0' before the intersperse, but I guess it will be buffering whole files, so it makes no difference.

**Comment by vqvu** [comment]
@Marsup The way to do this without buffering is to do the flattening *after* you intersperse (since `flatMap = map().sequence()`), so that you intersperse between each inner stream instead of in between each chunk.

```javascript
var objects = _(images).map(function (url) {
// Transform to base64
})
.intersperse(_([','])) // Intersperse a stream instead of a string.
.sequence();

_(['[']).concat(objects).append(']').toArray(function (arr) {
  console.log(arr);
});
```

**Comment by Marsup** [comment]
I don't see how this would work with map, since I can't provide base64 representation immediately.

Is this the kind of thing you expected ?
```js
var objects = _(images).map(function (url) {
  // Transform to base64
  return _(request(url).pipe(base64.encode()));
})
  .intersperse(_([','])) // Intersperse a stream instead of a string.
  .sequence();

_(['[']).concat(objects).append(']').toArray(function (arr) {
  console.log(arr);
});
```
If so it doesn't work.

**Comment by vqvu** [comment]
I was thinking more along the lines of

```javascript
var objects = _(images).map(function (url) {
  var image = _(request(url).pipe(base64.encode()));
  return _(['{"name":"' + url + '","content":"']).concat(image).append('"}');
})
.intersperse(_([',']))
.sequence();
```

Does that not work? What do you mean by "can't provide base64 representation immediately"? You don't have to. You're just returning a stream, and the stream is lazily evaluated.

**Comment by Marsup** [comment]
This is very weird, I tried the exact same code at home and it works. Maybe my work proxy messed up the stream somehow. I had several buffers interspersed by commas for a single image, I even had a comma first (right after the "[").

**Comment by Marsup** [comment]
Well it seems to work fine today at work, I guess I did something wrong yesterday. Thanks a lot !

Do you think there's a way to do base64 (efficiently ?) without that dependency ? I tried `_(request(url)).splitBy('').batch(3).invoke('toString', ['base64'])` but I get `TypeError: Object � has no method 'copy'`. Also is there a way to split every n character that I don't see ?
