### ISSUE TITLE
Stream rewind

### ISSUE THREAD

**Issue by jeromew** [caolan/highland#201]
I was wondering if it could make sense to 'rewind' a stream.

In a sense `s.take(1)` could be reverted and allow for the representation of a sort of Turing Machine - http://en.wikipedia.org/wiki/Turing_machine

The way `streaming` is currently understood (as in node.js native streams) is uni-directional but it might make sense to have bi-directional transforms.

I am not sure `highland` is the right tool for the job in that case but wanted to spawn a (hopefully short) discussion.

**Comment by vqvu** [comment]
I don't see how rewinding `s.take(1)` would allow us to implement a Turing Machine. Do you mean using it as a back-tracking mechanism to implement non-deterministic Turing Machines? If so, you'd still need to find a way to revert the tape state, as the stream only represents the input state.

Also, I don't see how we can implement rewind without buffering every single token that every stream emits. We could provide a `toRewindable()` operation that returns a rewindable stream, but I don't see a compelling use-case.

I think people who want a rewindable stream actually just want an array + lodash (with maybe `highland` used at the beginning to build the array asynchronously), so I'm in the "`highland` is not the right tool" camp.

**Comment by jeromew** [comment]
Yes you are right that it would need buffering (at least up to a certain rewindable horizon / memory size) to make a stream rewindable.

I think that I am confused as to whether the first-order component should be the stream or the transform + trying to imagine this on a multi-machine setup where the stream would flow on a cluster of machine. This is definitely not 'highland-only' ;-). I bring it up in case it triggers some ideas for the architecture of the code.

**Comment by vqvu** [comment]
For me, the core of Highland is

1. an async stream (i.e., the generator function) and
2. consumption of that stream (`pull` and `consume`)

Everything else is just nice sugar on top.

**Comment by jeromew** [comment]
I think what I am refering to is something similar to https://github.com/jadejs/token-stream but with the lazy evaluation & async'ness.

**Comment by jeromew** [comment]
I close this just to remove the noise. The main point was that since highland is lazy, there are cases when only one token flows from start to finish. In that case, it could be interesting to be able to rewind to do things like `token-stream` does.
