### ISSUE TITLE
Identity And Other Logical Operators

### ISSUE THREAD

**Issue by svozza** [caolan/highland#203]
I often find my self having to stream transformation only if a certain condition is met so it ends up looking something like this:

```javascript
var xs = [1, 2, 3, 4, 5]

_.seq( 
    _.through(function (xs) {
        if (req.query.count == null) {
            return xs;
        }
        return xs.take(count)
    }),

    _.toArray(function (xs) {
        console.log(xs);
    })
)(xs);
```
That's quite clunky so what I actually do is:

```javascript
_.seq(

    req.query.count == null ? require('ramda').identity : _.take(count),

    _.toArray(function (xs) {
        console.log(xs);
    })
)(xs);
```
I think it would be nice to include an identity function in the operators section like with `_.not`. And while we're at it wouldn't do any harm to add `_.and` and `_.or`. What do people think? I could have a PR done for this very quickly.

**Comment by quarterto** [comment]
I'm against this. There's no reason to include these combinators in Highland, they're nothing to do with streaming. What's wrong with using Ramda like you're doing?

**Comment by svozza** [comment]
Nothing wrong with using Ramda at all but just because I don't mind that dependency doesn't mean others will. How come we have `_.not` and `_.add` then? They're not really anything to do with streaming either but they're very useful from a functional programming point of view, which I thought was one of the areas Highland was exploring.

**Comment by quarterto** [comment]
If I'd been involved with Highland [when `not` was added](https://github.com/caolan/highland/commit/6a76ba7f65573375c6f00182e4c5dd5841af179f) I'd have protested then as well :smile:

**Comment by svozza** [comment]
Hehe. It's a good point though, I think we either have all the common operators or none.

**Comment by StreetStrider** [comment]
If it's already composable, why one should copy this stuff into the Highland source tree? Focus on keeping things DRY.

**Comment by jeromew** [comment]
I think that once we will all agree on highland's extensibility mechanism we will maybe need to cleanup what belongs and what does not belong to the core.

**Comment by StreetStrider** [comment]
@jeromew, great point. :+1:

**Comment by svozza** [comment]
This escalated quickly! :) I actually agree with @quarterto, the operators probably don't belong here. I just thought there was a reason I didn't understand as to why they were there and wanted to add the 'missing' ones for completeness. 

That said, I still think the if/else functionality for applying a tranform is useful. Is there a way of doing it using the chained syntax without that clunky `through`?

**Comment by jgrund** [comment]
Beyond that, we should rework the docs as currently they state:

> Re-thinking the JavaScript utility belt

Which links to lodash, underscore, and async.

Also, the docs alias `highland` to `_` which is usually the variable used by lodash and underscore; which can lead to further confusion.

**Comment by jeromew** [comment]
well I think that @caolan had the idea of 'rethinking the javascript utility belt' ;-) and maybe show that with highland, `_` could replace those 3 libraries.

I'll leave any change on this sentence to him ;-)

@svozza I haven't tried it and am not familiar with it but I think the if/else can be done via a stream redirection next(stream)

**Comment by ariutta** [comment]
Yes, it did appear @caolan intended for highland to replace lodash, etc. It would be awesome to include examples of how to extend highland to use methods from lodash, like:

```js
var highland = require('highland');
var lodash = require('lodash');
var _ = highland.extend(highland, lodash);

// based on example from lodash docs
_.intersection([1, 2, 3], [5, 2, 1, 4], [2, 1])
.toArray(function(result) {
  // → [1, 2]
});
```

**Comment by vqvu** [comment]
@svozza I don't think there's a way to do it using the chained syntax without `through`, but I don't agree that it's clunky.

```javascript
_([1, 2, 3, 4])
    .through(req.query.count == null ? require('ramda').identity : _.take(count))
    .toArray(_.log)
```

This looks exactly like the code you went with, except with an extraneous `through`.

**Comment by svozza** [comment]
Yeah, I was overcomplicating it before, that's just as nice a way of doing it.
