### ISSUE TITLE
Source link in docs should point to correct commit.

### ISSUE THREAD

**Issue by vqvu** [caolan/highland#205]
The source link for functions in the documentation should point to the tag for the release, and not to the master branch.

**Comment by vqvu** [comment]
Also, we'll want to change references to `rawgithub.com` to `cdn.rawgit.com` in light of #272. See #271 for the fix.

**Comment by svozza** [comment]
I actually thought that fix I merged resolved this but I didn't even see it was on that gh-branch. I've created a pull request with the necessary changes.

**Comment by jeromew** [comment]
The {{tag}} replacement was not beeing replaced with the tag version number upon `grunt build'. Should be fixed now.
