### ISSUE TITLE
Memory leak when destroying an observer.

### ISSUE THREAD

**Issue by jgrund** [caolan/highland#208]
Consider:

```
var _ = require('highland');

var s = _(function (push, next) {
  setTimeout(function () {
    push(null, 1);
    next();
  });
});

setInterval(function () {
  console.log(s._observers[0]._incoming.length);
}, 1000);

var s2 = s.observe();

s.each(function () {});

s2.destroy();
```

`s._observers` will still contain `s2` even though we have called `destroy` on it. This is because we never actually remove the observers like we do with consumers.

Because s2 is still buffering after being destroyed, this leads to a memory leak.

**Comment by jgrund** [comment]
Bump, is this an actual bug or am I misunderstanding something?

**Comment by vqvu** [comment]
Yep. This is a bug. I'll take a look at your PR.
