### ISSUE TITLE
Having trouble understanding chaining

### ISSUE THREAD

**Issue by Yomguithereal** [caolan/highland#210]
Hello,
Can someone explains me why this works

```js
var t = _([1])
t.map(function(i) {return i + 1}).apply(_.log);
```

and this does not (throw `Error: Stream already being consumed, you must either fork() or observe()`)?

```js
var t = _([1]);
t.map(function(i) {return i + 1})
t.apply(_.log);
```

Sorry in advance if the answer is obvious and possible to sum up to a RTFM.

**Comment by spro** [comment]
When you apply a function to stream `t`, you are not modifying `t` in place, but instead creating a new stream. Your example is equivalent to:

```js
var t = _([1]);
var s = t.map(function(i) {return i + 1})
s.apply(_.log);
```

**Comment by Yomguithereal** [comment]
This makes sense. Thanks a lot @spro.
