### ISSUE TITLE
Would it be a nice helper?

### ISSUE THREAD

**Issue by yangit** [caolan/highland#211]
Would it be nice helper? Or am I missing how this can already be done?
This is kind of reverse to _.pluck except it also works on zipped streams.

```
//_.assign
//turn zipped streams into stream of objects with assigned properties
//usage:

H([1, 2, 3]).zipAll([['bob', 'alice', 'john'], ['red', 'blue', 'green']])
    .map(assign('id', 'name', 'color'));
//=> [ { id: 1, name: 'bob', color: 'red' },
//     { id: 2, name: 'alice', color: 'blue' },
//     { id: 3, name: 'john', color: 'green' } ]

H([1, 2, 3]).map(assign('number'));
// => [ { number: 1 }, { number: 2 }, { number: 3 } ]


//implementation
var assign = function () {
    var args = Array.prototype.slice.call(arguments);
    return function (array) {
        var obj = {};
        if (array && array.constructor === Array) {
            array.forEach(function (item, index) {
                if (args[index]) {
                    obj[args[index]] = item;
                }
            });
        } else {
            if (args[0]) {
                obj[args[0]] = array;
            }
        }
        return obj
    }
};

```

Do you want PR?

**Comment by quarterto** [comment]
This doesn't need to be in Highland; it has nothing to do with streaming. Your `assign` could be used as-is with `Array.prototype.map`, or `async.map`, or `_.map`, etc.

**Comment by yangit** [comment]
Just like _.log, _.pluck they are also used with _.map.
Ok. I got your point.

**Comment by jeromew** [comment]
@yangit I think that @quarterto wants to keep the highland footprint low (mainly the streaming, pull, consume) primitives. We are now working on 3.0.0 and then we will work on extensibility so that utility libraries can be built on top of highland.
