### ISSUE TITLE
_.pluck to return x[prop].bind(x) if it encounters a function.

### ISSUE THREAD

**Issue by yangit** [caolan/highland#213]
Would it make sense for _.pluck to always bind plucked function to same object?

      return x[prop].bind(x)
I.e. when I want to save mongoose model I could

    var cat = new Cat({name:'Alice'}) 
    _.([cat]).pluck('save').nfcall()

Now I have to 
```
var cat = new Cat({name:'Alice'}) 
_.([cat]).map(function(obj) {
     obj.save.bind(landmark);
}).nfcall()
```

Are there are use cases when we want to unbind function?

**Comment by quarterto** [comment]
There's [`invoke`](http://highlandjs.org/#invoke) for this.

**Comment by yangit** [comment]
But invoke does not work with async functions.

**Comment by yangit** [comment]
But invoke does not return results from callback.

**Comment by yangit** [comment]
Sorry I did not mention that I want to consume results from callback like that.
```
var cat = new Cat({name:'Alice'}) 
_.([cat]).map(function(obj) {
     obj.save.bind(landmark);
}).nfcall().flatten().each(_.log)
```

**Comment by quarterto** [comment]
Oh, I see. Hmm. I'm still not sure. Underscore's pluck doesn't bind, and async doesn't even have pluck. Personally, I'd use `_.bindAll` from Underscore to solve this, but I can see the benefit of doing it this way round. What do other people think?

**Comment by vqvu** [comment]
Underscore's `pluck` doesn't bind, so I don't think we should either. Not to mention that, strictly speaking, this would break back-compat.

@yangit I would recommend just writing your own mapper to do this.

```javascript
function pluckAndBind(prop) {
    return function (x) {
        var val = x[prop];
        if (_.isFunction(val)) {
            val = val.bind(x);
        }
        return val;
    }
}

_([cat]).map(pluckAndBind('save')).nfcall().flatten().each(_.log);
```

**Comment by yangit** [comment]
After thinking about it I agree. Autobinding is somewhat vague feature which probably should not happen behind the scenes.
