### ISSUE TITLE
.zip'ing observed streams causes back pressure.

### ISSUE THREAD

**Issue by yangit** [caolan/highland#215]
I assumed that once you  .observe() stream. Slave can under no circumstances pause master. Is that wrong?
I.e.
```
var master = _([1, 2, 3]);
var observer = master.observe();
var logger = master.observe();
logger.each(_.log);
master.resume();
// Output is [1,2,3] and that is expected.
```
Now we add .zip to observer and that somehow stops master from emitting all values
```
var master = _([1, 2, 3]);
var observer = master.observe();
var logger = master.observe();
var total = observer.zip([4,5,6]).toArray();
logger.each(_.log);
master.resume();
// Output is [1] and I expected [1,2,3]
```

Did I misunderstood documentation?

**Comment by vqvu** [comment]
No, you're right. This is a bug.

**Comment by yangit** [comment]
How long until this fix makes it to NPM?

**Comment by quarterto** [comment]
This is in 2.4.0, released on February 17th.
