### ISSUE TITLE
_.log to return passed object?

### ISSUE THREAD

**Issue by yangit** [caolan/highland#216]
```
_.log = function (i) {     
   console.log.apply(console, arguments); 
   return i
};
```
So that we can:

    _.([1,2,3]).map(_.log).each(doSomething)   //nothing consumed but when consumed I will see log here.

I use it a lot for debug etc.. Again I know it has nothing to do with streams...

**Comment by quarterto** [comment]
You can use `_.doto`:

```js
_.([1,2,3]).doto(_.log).each(doSomething)
```
