### ISSUE TITLE
apply called after stopOnError

### ISSUE THREAD

**Issue by jgrund** [caolan/highland#224]
`apply` is called after `stopOnError`. Example:

```
highland([new Error('foo')])
  .stopOnError(function () {})
  .apply(function (x) {
    console.log('I should not be called.');
  });
```

In this case `x` comes through as `undefined`.

**Comment by vqvu** [comment]
This isn't a bug. You're calling `apply` on an empty stream, so no arguments are begin passed to your callback function. This is the same situation as

```javascript
_([]).apply(function () {
    console.log('I will be called.');
});
```

Maybe what you want is `each`?

**Comment by jgrund** [comment]
Thanks, that makes sense. Do you think a note on the docs highlighting this use case would be helpful?

**Comment by vqvu** [comment]
I'm always happy to add clearer docs. What do you have in mind? Something
like this?

> `f` will always be called, even when the stream is empty.

Or are you talking about a pointer to `each` in the `apply` docs?

**Comment by jgrund** [comment]
Yes, the former.  Perhaps something like:

>  `f` will always be called when the `nil` token is encountered, even when the stream is empty.

I guess my confusion is I was thinking `stopOnError` would cause downstream consumers to not receive any data. 

I understand that with `collect` sending it's internal array when it receives a `nil` token, and `stopOnError` sending `nil` downstream is what causes this behavior.

I guess I could use `errors` in this case to stop `apply` from being called as well.

**Comment by vqvu** [comment]
Actually `errors` won't stop `apply` from being called. `nil` will always
be passed on even if you don't push through anything with `errors`. The
only way to stop `apply` from being called is to use `consume` to suppress
the `nil`.

I imagine what you want to do is to only call `apply` if the steam
completes with no error. This is pretty tricky to do with the current
transforms. You'd have to implement your own version of `pick`.

Example:

```javascript
function applyOnNoError(f) {
    return function (s) {
        return s.collect().pull(function (err, x) {
            if (err) {
                // do nothing or handle error
            }
            else {
                f.apply(null, x);
            }
        });
    }
}

_(function (push, next) {
    push(new Error ());
    push(null, _.nil);
}).through(applyOnNoError(_.log));
// should log nothing
```

Your suggested doc change makes sense. Can you make a PR for it? I'm away
from my computer (typing this on my phone), so I can't do it myself.

Yes, the former. Perhaps something like:

f will always be called when the nil token is encountered, even when the
stream is empty.

I guess my confusion is I was thinking stopOnError would cause downstream
consumers to not receive any data.

I understand that with collect sending it's internal array when it receives
a nil token, and stopOnError sending nil downstream is what causes this
behavior.

I guess I could use errors in this case to stop apply from being called as
well.

—
Reply to this email directly or view it on GitHub
<https://github.com/caolan/highland/issues/224#issuecomment-74502158>.

**Comment by jgrund** [comment]
Yes, you are correct. I was thinking how `errors` doesn't send `nil` explicitly the first time it receives an error. It will pass any upstream `nil` through though.

I'll send a PR.

**Comment by jgrund** [comment]
@vqvu Pushed a pr for this doc fix.
