### ISSUE TITLE
setEncoding

### ISSUE THREAD

**Issue by quarterto** [caolan/highland#227]
Regular node `Readable` streams have `setEncoding`. Consumers expecting a `Readable` but getting a Highland stream might trip up on this. However, it effectively mutates the underlying data, which we discourage. Thoughts?

---

If `setEncoding` didn't do mutable things we could easily implement it as

```js
Stream.prototype.setEncoding = function(enc) {
  return this.map((s) => s.toString(enc));
};
```

**Comment by vqvu** [comment]
Does `seEncoding` even work in object mode? Can we just say Highland is an object-mode-only `Readable`? Actually, does highland streams even advertise as a `Readable`? We have our own `pipe`, but that's not the same thing, right?

Should we just provide a `toNodeStream` method that will return an actual `Readable` instead? Adding a `setEncoding` transform solely for the purposes of interop seems unnecessary.

**Comment by quarterto** [comment]
You're right, I was under the impression it had `.readable = true` but it doesn't. `setEncoding` doesn't seem to care about `objectMode`. An easy way of consumers doing `toNodeStream` would be `highlandStream.pipe(through())`.
