### ISSUE TITLE
Release new highland version

### ISSUE THREAD

**Issue by jgrund** [caolan/highland#231]
There have been a number of features / bugfixes that have landed on the 2.x branch since 2.3.0.

It would be useful to push a new release so we can make use of these changes.

**Comment by LewisJEllis** [comment]
Pinging @jeromew for this; he has npm publish access.

**Comment by jeromew** [comment]
@jgrund @LewisJEllis I just came back online after a trip. I will bump a new version in a few hours

**Comment by jeromew** [comment]
2.4.0 is published.

**Comment by jgrund** [comment]
@jeromew @LewisJEllis Thanks!

**Comment by ibash** [comment]
Thanks!
