### ISSUE TITLE
ES6 Generators

### ISSUE THREAD

**Issue by svozza** [caolan/highland#233]
With the release of Node v0.12 - and io.js - there's going to come a time soon when it'll make sense to support generators or just ES6 iterators in general. These seem to really lend themselves well to Highland's model and it looks like it would be pretty trivial to implement too. Not sure if it's too simplistic but it seems all that's required is adding the following to the else branch where we ducktype promises:

```javascript
else if (_.isObject(xs)) {
        if (_.isFunction(xs.then)) {
            // probably a promise
           ...
        }
        else if (_.isFunction(xs.next)) {
            //probably an iterator
            return _(function (push, next) {
                try {
                    var iterVal = xs.next();
                    if (!iterVal.done) {
                        push(null, iterVal.value);
                        next();
                    }
                    else {
                        push(null, nil);
                    }
                }
                catch (err) {
                    push(err);
                    push(null, nil);
                }
            });
        }
        else {
            // write any errors into the stream
           ...
        }
    }
```

This allows code like this:

```javascript
function* gen() {
    for (let i = 0; i < 3; i++) {
        yield i;
    }
}

_(gen()).toArray(_.log)
//=> [ 0, 1, 2 ]
```
Or even:

```javascript
function* fibonacci() {
  let a = 0, b = 1, c;

  while(true) {
    yield a;
    c = a + b;
    a = b;
    b = c;
  }
};

_(fibonacci()).take(5).toArray(_.log);
//=> [ 0, 1, 1, 2, 3 ]
```

I'm not saying this has to happen now but it's something to keep in mind. What are people's thoughts?

**Comment by svozza** [comment]
Dammit, I did a search in issues but somehow missed #131

**Comment by vqvu** [comment]
+++1

My only comment is that the try-catch block should only be around the `xs.next()`. The rest are highland-internal things that should not throw. More importantly, we don't want to suppress exceptions that should happen.

For example, `toArray` may throw. In the sync case, the exception will propagate up to one of the `push` or `next`. We don't want to suppress that exception.

In general, try-catch blocks in transforms should only go around user-provided functions. Never highland-provided ones.

**Comment by vqvu** [comment]
Closing because duplicate. I've added a link back to here from the other issue.

**Comment by svozza** [comment]
Agreed about the catch, not actually sure why I did it that way in the first place!
