### ISSUE TITLE
Web doc generation?

### ISSUE THREAD

**Issue by deitch** [caolan/highland#241]
Silly question, but what did you use to generate the highlandjs.org Web site. Yeah, it is GHP, but it looks like it is basically your README.md put through some nice formatting, indexing, navigation-generating engine. What was the process? I have a number of projects that would benefit from cleaning up like that.

Thanks!

**Comment by quarterto** [comment]
They're extracted from the comments in the source by @caolan's tool (scrawl)[https://github.com/caolan/scrawl] and compiled into the docs you see by [this grunt task](https://github.com/caolan/highland/blob/master/tasks/docs.js). It's definitely not a plug-and-play documentation generator, but you could possibly adapt it to your needs.

**Comment by deitch** [comment]
Thanks @quarterto 

I will see if it fits.

**Comment by quarterto** [comment]
If you're looking for something a bit easier out of the box you can use JSDoc with [readthedocs.org](https://readthedocs.org/) via [jsdoc-toolkit-rst-template](https://github.com/juhamust/jsdoc-toolkit-rst-template)

**Comment by deitch** [comment]
Heh, long history with jsdoc. I actually have a pretty decent README.md in place, the challenge is turning it into a good site usable for ghpages (or other static host), so it has links, formatting, etc.
