### ISSUE TITLE
`through` a Node read-write stream doesn't seem to write

### ISSUE THREAD

**Issue by joshdmiller** [caolan/highland#243]
```js
var mapStream = require( 'map-stream' );

var map = mapStream( ( f, cb ) => {
  console.log(f);
  cb( null, f + 1 );
});

_([1,2,3])
.through( map )
.map( (v) => {
  console.log("this will never run", v);
  return v;
})
.toArray( (a) => {
  // and this is an empty array
  console.log(a);
});
// Ouputs:
// 1
// 2
// 3
// []
```

The map seems to be executing fine, but any subsequent highland streams receive no input, though `map-stream` should be read-write. I'm fairly certain this worked in a version of Highland from mid-2014, but I'd have to check.

Other things I've tried.

* Piping to map and wrapping the result in a highland stream: `_(_([1,2,3]).pipe(map))`. This produces the same result.
* Converting the defined map stream to a highland stream: `map = _(map)`. This makes the read stream work and the values propagate, but not the write part of the stream, so the values never increment as defined.

Is my expectation wrong?

PS: This was discovered in a unit test, where I'm attempting interop with existing Gulp plugins, which are most often defined using `map-stream`. So I don't have control over the interim streams, but I want to start and end with a highland stream

**Comment by vqvu** [comment]
Looks like `map` emits the result as soon as the highland stream is piped to it, so then the subsequent pipe to a regular highland stream doesn't get anything besides a `nil`.

We pause the target in `through` though (https://github.com/caolan/highland/blob/master/lib/index.js#L2459), so seems like a bug in `map-stream`?

Paused readables are supposed to stop emitting `data` events (http://nodejs.org/api/stream.html#stream_readable_pause), but it seems the map stream does it anyway?

```javascript
var map = mapStream(function(f, cb) {
        cb( null, f + 1 );
});

map.on('data', function (x) {
    console.log(x);
});

// Pause the stream, should stop emitting data.
map.pause();
map.write(2);
// emits 3
```

**Comment by joshdmiller** [comment]
Thanks for the prompt response! I see exactly what you mean and I filed an issue (dominictarr/map-stream#14) at `map-stream` too so we can sort this out. I'll report back...

**Comment by joshdmiller** [comment]
The owner of the upstream lib confirmed that `pause` is not implemented, so I'm going to implement it there. As such, I think we can close this. Thanks again for your help! I appreciated the specific references.
