### ISSUE TITLE
wrapCallback and callbacks with more than two arguments

### ISSUE THREAD

**Issue by bolus** [caolan/highland#246]
Hi,

Why does wrapCallback ignore the third argument if there is one?

Wouldn't it be easy to check if there are more than two arguments and if so to put an array of these arguments into the stream?

Best regards,
Daniel

**Comment by quarterto** [comment]
I agree that it would be good to support callbacks with multiple parameters, and it's easy enough to implement, but I think it feels a bit weird to emit single values in some cases and arrays in others. We might end up in a case where a callback is called with a different number of arguments at different times, and that would get hard to abstract over.

Perhaps a `wrapCallbackN` would work? You'd pass it a function and expected number of arguments and it would always emit an array of that length. Something like:

```js
_.wrapCallbackN = function(fn, n) {
  return _.wrapCallback(function(...args, cb) {
    fn(...args, function(e, ...results) {
      cb(e, ensureArrayLength(n, results));
    });
  });
}
```

**Comment by bolus** [comment]
Isn't this the same problem that the [EventEmitter Stream constructor had](https://github.com/caolan/highland/issues/60)?

Maybe that code can be reused?

**Comment by quarterto** [comment]
Ah, good find. Adding `mappingHint` to `withCallback` is a good idea, I'll send a pull request in a bit.

p.s. We usually avoid optional parameters, because they don't work with currying, but since this is a constructor function, not a stream method, that doesn't apply here (unless anyone disagrees!)

**Comment by quarterto** [comment]
⇒ #247

**Comment by bolus** [comment]
Thanks, @quarterto!

**Comment by vqvu** [comment]
Reopening until #247 is merged.

**Comment by dypsilon** [comment]
Please consider solving #334 with mappingHint.

**Comment by vqvu** [comment]
@quarterto, you you have time to finish up #247?

**Comment by quarterto** [comment]
Wow, sorry, that totally slipped off my radar. I'll have a look this afternoon.
