### ISSUE TITLE
Multiple parallel streams

### ISSUE THREAD

**Issue by ccorcos** [caolan/highland#255]
Again, I'm trying to integrate Meteor with Highlandjs so this may seem like an odd question. Basically I want to know if you can have two streams going side by side, so I can do something like `.map(function(stream1values, stream2values) { ...`

Heres' the motivation:

`sub = Meteor.subscribe( ... )` will subscribe to data from the server. It returns an object so you can call `sub.stop()` when you want to clean up.

I created a function that will do this cleanup for me.

```coffee
# will stop a meteor subscription when rerun or stopped
subscribe = _.curry((f, source) ->
  sub = null
  source.consume((err, x, push, next) ->
    if err 
      push(err)
      next()
    else if x is _.nil
      sub?.stop?()
      push(null, x)
    else
      sub?.stop?()
      sub = f()
      push(null, x)
      next()
  )
)
```

`sub.ready()` is a "reactive" function that will tell you if the subscription is ready, i.e. the server is done sending the data to the client. I created a function that will convert this meteor reactivity into a highland stream:

```coffee
autorunStream  = (f) ->
  stream = _()
  c = Tracker.autorun ->
    results = f()
    stream.write(results)

  stream.observe().through(onDone(() ->
    c.stop()
  ))
  return stream
```

Thus, we can now do this `readyStream = autorunStream(-> sub.ready())`

So here's what I have so far:

```coffee
search.fork()
  .debounce(500)
  .through(subscribe((query) ->
    Meteor.subscribe('search', query)
  )).map (query) ->
    # return the results of the query
```

However, I want to render a loading template while the subscription isn't ready, and render the results once it is ready. What I want to be able to do is something like this:

```coffee
renderStream = search.fork()
  .debounce(500)
  .through(subscribe((query) ->
    Meteor.subscribe('search', query)
  )).map (query, ready) ->
    if ready
      # return an html string of the results based on the query
    else
      # return an html string that says loading...
```

I'm not sure this is possible or even a good way of doing it. The idea is to have the query stream and the ready stream side by side. Its as if they're merged (the map will run when either changes), but the values are separated and passed as separate arguments.

At the end of the day, `renderStream` needs to be a stream of renderable strings.

Thanks for the help

**Comment by vqvu** [comment]
First of all, `autorunStream` shouldn't be using `observe`. An observer cannot affect the source stream. Since you observe `stream` but return the observer, you'll never ever get any data (since nothing will `resume` `stream`). `onDone` does data passthrough anyway, so you don't even need the `observer`. It's `done` (which is a terminal operation) that needed the `observe` so that it doesn't `resume` the source stream too early.

Secondly, you'll want to always end streams (unless what you have is logically an infinite stream).
```
  c = Tracker.autorun ->
    results = f()
    stream.write(results)
    stream.end() # Should end the stream.
```

Onto the main question. I can't think of an easy way to implement what you're asking for, but I don't think it's necessary. The easiest way is to have `subscribe` also provide the subscription, so
```javascript
sub?.stop?()
sub = f()
push(null, [x, sub]) # I made an array, but it could be an object if you want
next()
```

then use `map` to return a stream that first emits your loading text, then emit your data once `sub.ready()` returns.
```javascript
map(function (arry) {
    var query = arry[0],
        sub = arry[1];

    var data = autorunStream(sub.ready.bind(sub))
        .map(renderData.bind(null, query));

    return _(function (push, next) {
        push(null, "Loading...");
        next(data); // Delegate to the data stream.
    });
});

function renderData(query) {
    // Do render here.
}
```

Then you use `switch` to always stay with the latest query.

```javascript
var renderStream = search.fork()
    .debounce(500)
    .through(subscribe(Meteor.subscribe.bind(Meteor, 'search')))
    .map(function (arry) {
        ...
    })
    .switch();
```
```

**Comment by ccorcos** [comment]
Hmm. So I've come up with this concept of "joining" streams where you and stack multiple streams next to each other. Here's the basic concept in the form of a test:

```js
_ = highland
a = _()
b = null
a.through(join(function(x){
  b = _()
  b.write(x*2)
})).through(multi(_.each, function(x,y){
  console.log(x,y)
}))
a.write(1)
// => 1, 2
b.write(3)
// => 1, 3
b.write(4)
// => 1, 4
a.write(3)
// => 3, 6
b.write(7)
// => 3, 7
```

`join` maps over a `source` stream creating `child` streams. These child streams are ended when the next value from the source is emitted (`switchOnNext`). It returns a multiStream which is an array of the values in both streams whenever either stream changes.

`multi` simply assumes that a stream has an array of values meant to be passed as arguments to some transform.

Anyways, here's what I've got so far:

```coffee
join = _.curry((f, source) ->
  multiStream = _().through(stopOn(source))

  val1 = null
  val2 = null

  emit = ->

    if val1 instanceof Array and val2 instanceof Array
      multiStream.write(val1.concat(val2))
    else if val1 instanceof Array
      multiStream.write(val1.concat([val2]))
    else if val2 instanceof Array
      multiStream.write([val1].concat(val2))
    else
      multiStream.write([val1, val2])
      
  # not observe?
  source.fork()
    .map(f)
    .through(switchOnNext)
    .each (x) ->
      val2 = x
      emit()

  source.fork().each (x) ->
    val1 = x
    emit()

  return multiStream
)

@multi = (transform, f) ->
  (source) ->
    source.through(transform((arr) -> 
      f.apply(null, arr)
    ))
```





takeUntil = _.curry((stream, source) ->
  first = true
  done = false
  source.consume( (err, x, push, next) ->
    if first
      stream.pull ->
        if not done
          push(null, _.nil)
          done = true
      first = false
    if err
      push(err)
      next()
    else if x is _.nil
      done = true
      push(null, x)
    else if not done
      push(null, x)
      next()
  )
)

switchOnNext = _.curry((source) ->
  stop = null
  source.flatMap (maybeStream) ->
    if _.isStream(maybeStream)
      stream = maybeStream
      if stop
        stop.end()
        stop = null
      stop = _();
      stream.through(takeUntil(stop))
    else
      _([maybeStream])
)


onDone = _.curry((f, source) ->
  source.consume((err, x, push, next) ->
    if err 
      push(err)
      next()
    else if x is _.nil
      f()
      push(null, x)
    else
      push(null, x)
      next()
  )
)

stopOn = (stream, source) ->
  stream.through(onDone(-> source.end()))

# a function creates a stream and we get back 2 parallel streams

**Comment by vqvu** [comment]
I don't have time to look closely right now, but a few things that I noticed:

1. You can only call `write`/`end` on a stream that was constructed with no generator (i.e., `_()`). That's the only case where we guarantee that it works. Your `multiStream` was not constructed this way.It's actually the child stream of the `_()` that was created by your `stopOn` function.

2. It's generally not needed (or encouraged) for you to use the `write`/`end` API when writing transforms. It's mostly meant for interop with Node streams. In some cases though (like `switchOnNext`), it is easier to use `write`, and that's fine.

3. `fork` is probably fine in this case, but you may not don't want to call `each` synchronously like that.

4. What you probably want is something similar to [zipAll](https://github.com/caolan/highland/blob/master/lib/index.js#L2126), except without waiting for all zipped streams to emit a value (L2141) and without reseting the array every time you emit some thing new (L2153). Though maybe it is worth emitting *copies* of the buffer instead of the buffer itself as a defensive measure. Note that a `zipAll`-like implementation would make `stopOn` no no longer necessary.

  Maybe call this `snapshot`? For viewing the current state of a stream of streams?

4. Then, you can implement `join` by using `snapshot`. Generally, when writing transforms, you want to keep their scope as small as possible, so that they're easier to compose. Doing it like this lets you reuse `snapshot` in other places.

**Comment by vqvu** [comment]
Oh and your `switchOnNext` seems weird. If you get a thing that's not a stream, you turn it into a stream that doesn't get stopped once the next thing gets push? If you just want to coerce every element into a streams, this works just as well

```javascript
stream.map(_) // Apply the constructor == coerce
    ...
```

You can also just blindly call the constructor and it'll do the correct coercion for you.

```javascript
stream = _(maybeStream);
if (_.isStream(maybeStream)) {
    console.log(stream === maybeStream) // => true
}
```

**Comment by ccorcos** [comment]
1. Hmm, I was under the impression that this could create a new stream `_()` that stops when the source stream stops `.through(onStop(source))`.

```coffee
stopOn = (stopStream, source) ->
  stopStream.through(onDone(-> source.end()))

@join = _.curry((f, source) ->
  multiStream = _().through(stopOn(source))
  # ...
)
```

Or are you saying that this would be better instead?

```coffee
@join = _.curry((f, source) ->
  multiStream = _()
  # ...
  return multiStream.through(stopOn(source))
)
```

2 and 3. So you're right that I don't actually want to call each, but the funky thing is that multiStream is disconnected from the source and the parallel stream in terms of consumption.

```coffee
  multiStream = _().through(stopOn(source))

  # parallel stream
  source.fork()
    .map(f)
    .through(switchOnNext)
    .map (x) ->
      val2 = x
      emit()

  # source stream
  source.fork().map (x) ->
    val1 = x
    emit()
```

Suppose I call `multiStream.each(_.log)`. Nothing should happen because the source stream consumed. 

4. How [this stream](https://github.com/caolan/highland/blob/master/lib/index.js#L2151) ended without calling `switchOnNext` or something like that?

**Comment by ccorcos** [comment]
So this turns out to be a rather elegant solution :)

```coffee
join = _.curry((f, source) ->
  source.map (x...) ->
      f.apply(null, x).map (y...) ->
        return x.concat(y)
    .through(switchOnNext)
)

multi = (transform, f) ->
  (source) ->
    source.through(transform((arr) -> 
      f.apply(null, arr)
    ))
```

Here's how it tests out:

```js
_ = highland
a = _()
b = null
a.through(join(function(x){
  b = _()
  b.write(x*2)
  return b
})).through(multi(_.each, function(x,y){
  console.log(x,y)
}))

a.write(1)
// => 1 2
a.write(2)
// => 2 4
b.write(5)
// => 2 5
a.write(5)
// => 5 10
```

**Comment by ccorcos** [comment]
It even works for piling on more streams!

```coffee
corceArray = (x) ->
  if x instanceof Array
    x
  else
    [x]

join = _.curry((f, source) ->
  source.map (x) ->
      x = corceArray(x)
      f.apply(null, x).map (y) ->
        y = corceArray(y)
        return x.concat(y)
    .through(@switchOnNext)
)


multi = (transform, f) ->
  (source) ->
    source.through(transform((arr) -> 
      f.apply(null, arr)
    ))
```

```js
_ = highland
a = _()
b = null
c = null
a.through(join(function(x){
  b = _()
  b.write(x*2)
  return b
})).through(join(function(x,y){
  c = _()
  c.write(x+y)
  return c
})).through(multi(_.each, function(x,y,z){
  console.log(x,y,z)
}))
a.write(1)
// 1 2 3
a.write(2)
// 2 4 6
b.write(3)
// 2 3 5
b.write(5)
// 2 5 7
c.write(10)
// 2 5 10
a.write(4)
// 4 8 12
```

**Comment by vqvu** [comment]
Nice! I was thinking too general-case where you don't have the luxury to create a new stream every time the source emits a new value. This was probably me misunderstanding the use case a bit.

> Hmm, I was under the impression that this could create a new stream _() that stops when the source stream stops .through(onStop(source)).
> ...
> Or are you saying that this would be better instead?

Yep. That's the correct way to do it. Before, you were essentially writing to the wrong thing. What you had was equivalent to
```javascript
var src = _();
var multiStream = src.through(onStop(source));
multiStream.write(...);
```
What you actually want is to write to `src`.

> but the funky thing is that multiStream is disconnected from the source and the parallel stream in terms of consumption.

Yeah, you do have to call `each`. I just meant you might want to do it lazily.

```javascript
multiStream = _(function (push, next) {
// Call `each` in here. This won't be called until you need the data.
// Then `emit` can use `push` instead of `write`
});
```

> How this stream ended without calling switchOnNext or something like that?

That stream ends when `nil` is pushed [here](https://github.com/caolan/highland/blob/master/lib/index.js#L2135).
