### ISSUE TITLE
How to stream error ?

### ISSUE THREAD

**Issue by asafyish** [caolan/highland#257]
Hi,
We have a use case when we want to send an error on a highland stream, and catch it on the side in the err parameter, using a copied StreamError works correctly, otherwise it doesn't. For example:

```js
function StreamError(err) {
    this.__HighlandStreamError__ = true;
    this.error = err;
}

var stream = getStreamSomeWhere();

stream.end(new StreamError('something went wrong');
stream.pull(function(err, data) {
// err = 'something went wrong', like expected
});
```

Is there other why to achieve the same result without using a fake StreamError ?

**Comment by vqvu** [comment]
Why are you using `write` anyway? If you have a node stream, then emit an `error` event and use the node stream constructor. If you don't then use the `push` from the generator constructor.

**Comment by vqvu** [comment]
Also, your code sample doesn't make sense. `Highland#end` doesn't take an argument. If `stream` isn't a highland stream, why does `pull` exist?

**Comment by asafyish** [comment]
You are right, I didn't wrote the full details, stream is a TCP socket.

The first message I am sending on the stream is something like(side A):
```js
{service: 'db', cmd: 'get-big-data'}
```
On the receiving side(side B), I need to check if a command called 'get-bid-data' exist, if not - send back an error, here comes the tricky part, I want the error to be in the err parameter of pull (or consume for that matter) of side A.

Am I doing something completely off ?

**Comment by vqvu** [comment]
From your comments in #200, I think you can use `map` and throw the error without having to implement a whole `consume`.

Something like this?

```javascript
_(requests).map(function (req) {
    if (commandExists(req.db, req.cmd)) {
        // do command.
        return result;
    }
    else {
        throw new Error("Command " + req.cmd + " does not exist.");
    }
}).errors(function (err) {
    // send error through the wire.
}).each(function (res) {
    // send result through the wire
});
```

**Comment by asafyish** [comment]
Yeah it works, I am catching errors on highland stream, and send a special packet over the wire.
