### ISSUE TITLE
No args `zipAll`.

### ISSUE THREAD

**Issue by vqvu** [caolan/highland#263]
I think we need a version of `zipAll` that doesn't take any arguments. Instead, it assumes that's it's called on a stream of stream and zips the current stream, like how `sequence` and `merge` and `flatten` work.

I often find myself having to keep a single stream separate from the remaining array of streams just so I can call `zipAll`. It would be trivial to implement.

The question is, what do we call it? `zipAll` would be perfect but already taken, and who knows when 3.0 will land. `zipStream`?

**Comment by svozza** [comment]
How about `zipped`?

**Comment by vqvu** [comment]
A past tense verb sounds like a property of the stream (like `paused`) and
not a transform.

How about `zipUp`? `zipSelf`?

**Comment by svozza** [comment]
Yeah, you're right the tense of the verb doesn't work. I like `zipUp` best of the four we've suggested. That said, we could always do what they do in Haskell and actually what we do in with `reduce` and use something like `zipAll1`.

Of course, none of this would be a problem if I had have named this properly in the first place. `zipEach` would have been perfect and left `zipAll` free. The benefits of hindsight!
