### ISSUE TITLE
Linked documentation site (highlandjs.org) sends too much traffic to rawgit.com, impeding understanding

### ISSUE THREAD

**Issue by twhaples** [caolan/highland#272]
The documentation provided is flawed and difficult to read because of a big red banner across the screen:

http://highlandjs.org/
"This site or app is sending too much traffic to rawgit.com. Please contact its owner and ask them to use cdn.rawgit.com instead, which has no traffic limit."

**Comment by svozza** [comment]
Fixed by #271
