### ISSUE TITLE
FlatMap ordering?

### ISSUE THREAD

**Issue by ronag** [caolan/highland#281]
Does `flatMap` maintain ordering similar to RxJS [concatMap](http://reactivex.io/documentation/operators/flatmap.html) or does it not similar to RxJS [flatMap](http://reactivex.io/documentation/operators/flatmap.html)?

**Comment by vqvu** [comment]
`flatMap` is equivalent to Rx's `concatMap`. Rx's `flatMap` is equivalent to a `map` followed by a `merge`.

**Comment by ronag** [comment]
:+1:

Would be great to have a table comparing all the different ops like that. Maybe a future PR once I've got the hang of highland.
