### ISSUE TITLE
requesting a "window" transform for things like moving avg or convolution

### ISSUE THREAD

**Issue by daywiss** [caolan/highland#298]
I can't figure out a clean way to do something like a moving average. Here is an example of what I'm talking about. 

``` javascript
_( [1,2,3,4,5] )
  .window(3)
  .each(console.log)  //[1,2,3] , [2,3,4] , [ 3,4,5]  can do an average(or whatever) over each window
```

This is similar to batch, but batch will not remember previous values and emit them like this. Could also offer a PR if this seems like a good idea.

If this can be done with the current api and _without_ closures, do please educate me.

**Comment by vqvu** [comment]
There's no way to do this in the standard API, short of using `consume` to write your own. Is that what you mean by "without closures"?

I'm happy to accept a PR that implements this if you're up for it. Though it'd be nice to have the generic version of this (i.e., equivalent of `slidingBuffer(count, skip)` [from RxScala](http://reactivex.io/documentation/operators/buffer.html)).

With this operator, `batch(n) === slidingBuffer(n, n)`, and `window(n) === slidingBuffer(n, 1)` (almost). You'll still need to filter for the small windows at the end if you really don't want them.

**Comment by jeromew** [comment]
+1 on slidingBuffer if you want to try and send a PR.
@vqvu do you agree that the elements in the different sliding windows should be simple references to the original objects when the elements are objects ?

we also have to agree on what should happen when an error is found on the source. Maybe we could consider that a a window that does not contain `count` elements is always an error ?

**Comment by daywiss** [comment]
@vqvu All i meant without closures was accumulating a buffer as a side effect and emitting that in a map function, so yes consume could work.  And yes I do agree that window and batch are special cases of slidingBuffer. I can look into making a pr for this.

@jeromew I would assume that if a stream contains less elements than the window size it acts like toArray() just emitting the entire stream as an array of values.

**Comment by vqvu** [comment]
@jeromew Yes. Simple references, like `batch` already does. Windows that don't contain `count` elemenst simply emit the entire stream as arrays like @daywiss suggests.

Errors in the source should be passed on like normal. This may rearrange error and values. For example,

In stream:
```
1 -> error -> 2
```

Outstream: slidingBuffer(2, 1)
```
error -> [1, 2] -> [2]
```

This is all to match the current behavior of `batch` right now.
