### ISSUE TITLE
2.5.0 regression

### ISSUE THREAD

**Issue by ronag** [caolan/highland#303]
After updating to 2.5.0 from 2.4.0 we can no longer wrap express req objects. Works fine after reverting to 2.4.0.

e.g.

```javascript
app.post('/*', function(req) {
  console.log("#1");
  _(req).pipe(fs.createWriteStream("tmp");
  console.log("#2"):
})
```

error:

```
#1
TypeError: Cannot read property 'done' of undefined
    at Stream._generator (upload/node_modules/highland/lib/index.js:393:26)
    at Stream._runGenerator (upload/node_modules/highland/lib/index.js:944:10)
    at Stream.resume (upload/node_modules/highland/lib/index.js:806:22)
    at Stream._checkBackPressure (upload/node_modules/highland/lib/index.js:708:17)
    at Stream.resume (upload/node_modules/highland/lib/index.js:801:29)
    at Stream.pipe (upload/node_modules/highland/lib/index.js:890:7)
    at upload/build/index.js:204:35
    at Layer.handle [as handle_request] (upload/node_modules/express/lib/router/layer.js:82:5)
    at next (upload/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (upload/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (upload/node_modules/express/lib/router/layer.js:82:5)
    at upload/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (upload/node_modules/express/lib/router/index.js:321:12)
    at next (upload/node_modules/express/lib/router/index.js:261:10)
    at expressInit (upload/node_modules/express/lib/middleware/init.js:23:5)
    at Layer.handle [as handle_request] (upload/node_modules/express/lib/router/layer.js:82:5)
```

**Comment by quarterto** [comment]
Looks like we're inferring that `req` is an Iterator because it has a `next` method. We should probably check is something is a `readable` stream before the iterator check.

**Comment by jeromew** [comment]
yes @quarterto, the sequence in https://github.com/caolan/highland/blob/master/lib/index.js#L517 was added in this release for iterators et iterables.

currently the default Object case is the `readable` stream where we use `pipe` without checking the existence of pipe. we could check that `pipe` is a function early and consider we are in the stream case or have a test of the class of the object.

@svozza when you added the iterator/iterables case have you found another project where there is such a chain of type detection and do you have an idea how best we could change the current behavior to remove the regression ?

**Comment by svozza** [comment]
No, I've not found other libraries that detect iterators other than by the presence of a `next` function. I mean the most drastic fix would be for us to only support `Iterables` and their default `Iterator` but that would mean you couldn't do this any more:

```javascript
var map = new Map([['a', 1], ['b', 2]]);
_(map.values())...
```
Something mentioned in the [Mozilla docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) is that when you `toString()` an iterator you get back a string with word `Iterator` in it, I guess it would be similar to how we implement the `isArray` function now. That would probably only work with offical Iterators like those associated with `Array`, `Map`, `Set` etc (I doubt that custom iterators written by developers would have the correct `toString` method implemented). Tbh, I really don't like this as a solution but I'm struggling to think of anything better.

**Comment by jeromew** [comment]
what do you think about giving more priority to a test on `pipe` ? I think that as @quarterto mentioned it might solve the express use case.
@ronag do you confirm that the express `req` has a pipe function ? is it always a `readable` ?

**Comment by svozza** [comment]
Yeah, I think @quarterto 's suggestion is far preferable to mine, intuitively it makes sense that one of the first things we do is check whether an object we've been passed is a `Readable` stream. Failing early when passing in something Highland can't deal with is also a benefit of throwing in the default case. I can put together a PR for this right now if you want and we could do a `2.5.1` release maybe?

**Comment by jeromew** [comment]
Yes I think we can push a 2.5.1 easily ; only some docs were commited since 2.5.0 so we can use the grunt targets for this. 

There is https://github.com/rvagg/isstream with an isReadable method ; I don't know the effect that depending on `stream` would have on browserify though. I'd prefer something more lightweight

**Comment by svozza** [comment]
Yeah, I think that `isStream` thing is overkill and also it relies of `instanceof`, which is notoriously unreliable. Would it be enough to check for `pipe` and `_read`?

**Comment by jeromew** [comment]
In the code, we use `xs.pipe` and `xs.on` so maybe we can check these 2 and consider we are in the stream case. I guess that our polymorphic constructor is already a bit of a hack so maybe even just `pipe` would solve our problem.

I fear that we may hit this problem again down the road with custom librabries with `next` or `pipe` or whatever ; at one point maybe we will need adaptors for custom libraries because we won't be able to make everybody happy.

**Comment by svozza** [comment]
Yeah, I was thinking that it's getting a bit unwieldy. Even though it's really nice to be able drop various sources into the constructor and they'll just work (mostly!) I think you're right and we may have to go down the adapter route: perhaps as part of the extensions work we've planned post-3.0.

**Comment by vqvu** [comment]
For back compat, I think prioritizing the checks for `pipe` and `on` is the best short term fix.

What we probably really want is a separate `_.fromReadable`, `_.fromIterator`, etc and push the issue to the user, who would unequivocally have that information. That way, we don't have to worry about doing some generic coercion that may or may not work.
