### ISSUE TITLE
[request] distribute the browserified highland with the NPM package

### ISSUE THREAD

**Issue by sethkinast** [caolan/highland#309]
We use NPM to manage both Node modules and browser packages, instead of Bower.

It would be great if the `dist` folder could be distributed as part of the NPM package, instead of just `lib`.

**Comment by pajtai** [comment]
Just curious why don't require it in?

I use browserify too, and this is my workflow:

```
var highland = require('highland');
```

**Comment by Announcement** [comment]
@pajtai because that's not documented...

**Comment by vqvu** [comment]
@Announcement, can you clarify exactly what behavior is undocumented? Is it the ability to browserify a project that `require('highland')`? We can fix the documentation if it is missing something.

**Comment by pajtai** [comment]
I think it's implied from the homepage: http://highlandjs.org/

```
The high-level streams library for Node.js and the browser.

$ npm install highland
```

as in, saying it's for the browser and then showing an npm command implies it works with browserify, the way browserify is meant to work - by just requiring npms in on the browser.

**Comment by jeromew** [comment]
The doc also states "You can also integrate highland in your own browserify bundle using a classical browserify workflow, but this is beyond the scope of this documentation."
