### ISSUE TITLE
Each() doesnt invoke the stream

### ISSUE THREAD

**Issue by kharandziuk** [caolan/highland#311]
I have the problem with code below:
```
var
  H = require('highland'),
  fs = require('fs'),
  split = require('split');

var lineStream = fs.createReadStream('data-samples/sample.log').pipe(split());

H('data', lineStream).reduce(0, function(count) {
  return count + 1;
}).each(console.log); // I see nothing in console
```
Documentation says
```
To get the map iterator to be called, we must pull some data from the Stream. This is called a thunk, and some Highland methods will cause them (eg, each, done, apply, toArray, pipe, resume).
```
but I see nothing in console

**Comment by quarterto** [comment]
What's probably happening here is `resume` isn't being called on the underlying stream because you're just subscribing to the `data` event. Highland can directly consume Node streams; `H(lineStream)` should work.

p.s. we do also have a [`stream.split`](http://highlandjs.org/#split)

**Comment by kharandziuk** [comment]
Thanks for the answer. The code below works as expected:
```
var
  H = require('highland'),
  fs = require('fs');

var lineStream = fs.createReadStream('data-samples/sample.log');

H(lineStream).split().reduce(0, function(count, line) {
  return count + 1;
}).each(console.log);
```

Did I miss something or the library has no good examples?:)
Is it make sense to add this sample somewhere?

**Comment by quarterto** [comment]
`on('data')` hasn't been the proper way to work with Node streams since Node 0.6. There are examples of working with Node streams in the [examples section on highlandjs.org](http://highlandjs.org/#examples).

**Comment by svozza** [comment]
Maybe we should revisit the cookbook/examples idea:  #188 #204
