### ISSUE TITLE
require('highland') returns nothing

### ISSUE THREAD

**Issue by cappslock** [caolan/highland#312]
For whatever reason in the Node REPL, require('highland') fails:

```
var _ = require('highland');
console.log(_); // undefined
```

Additionally highland seems to be writing to the `_` variable on the global scope by default:

```
require('highland');
console.log(_); // stuff!
```

**Comment by quarterto** [comment]
[That's a quirk of the Node REPL](https://nodejs.org/api/repl.html#repl_repl_features). `_` is a special variable that refers to the result of the previous expression. Using a different variable name will work.

**Comment by cappslock** [comment]
Ahhhh. Thanks.
