### ISSUE TITLE
take() behavior

### ISSUE THREAD

**Issue by kharandziuk** [caolan/highland#314]
Consider a code below:

```
var tickStream = H(function(push, next){
  setTimeout(
    function() {
      log('tick');
      push(null);
      next();
    },
    300
  );
});

tickStream.fork().take(1).each(function(){ //
  console.log('some job');
});
tickStream.fork().each(function(){
  console.log('some other job');
});
```
Now I see the text below in console:
```
some job
some other job
```
but I want to have `some job` once and infinite sequence of `some other job`. How I can achieve the expected behavior?

And documentation says: `take() - Creates a new Stream` but in reality it ends the existed one

**Comment by svozza** [comment]
What about doing the following for your stream of one item:

```javascript
tickStream.observe().head().each(function(){ //
  console.log('some job');
});
```

**Comment by kharandziuk** [comment]
It works, thanks
