### ISSUE TITLE
Favicon for the doc pages.

### ISSUE THREAD

**Issue by Neppord** [caolan/highland#322]

**Comment by quarterto** [comment]
Good idea. We don't currently have an icon, though we do have a wordmark logo. Thoughts?

**Comment by Neppord** [comment]
Anything that helps me (and others) differentiate the docs from other *pinned* tabs in Chrome.

**Comment by quarterto** [comment]
Something like this?
![highland 32](https://cloud.githubusercontent.com/assets/631757/8352758/7838df5c-1b2f-11e5-800c-75c5ad9b9383.png)

**Comment by Neppord** [comment]
I think it might be a bit to skinny for a icon, a background color would help. but its a huge improvement!

**Comment by quarterto** [comment]
It looks alright in situ. It's live on [highlandjs.org](http://highlandjs.org), have a look! We can always iterate on it.

**Comment by Neppord** [comment]
yes! thanks!

**Comment by svozza** [comment]
Weird, it doesn't seem to be appearing on Firefox.

**Comment by Neppord** [comment]
I needed to release my cache.

Does that help?

torsdag 25 juni 2015 skrev Stefano Vozza <notifications@github.com>:

> Weird, it doesn't seem to be appearing on Firefox.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caolan/highland/issues/322#issuecomment-115234527>.
>


-- 
Samuel Ytterbrink
Webutvecklare

Fromspace

**Comment by svozza** [comment]
Restarting the browser fixed it!
