### ISSUE TITLE
parallel - limit stream buffers?

### ISSUE THREAD

**Issue by ronag** [caolan/highland#332]
As parallel is implemented right I believe it will buffer the entire sub streams, correct?

So if I'm processing large files in parallel I could essentially run out of memory?

**Comment by vqvu** [comment]
Yes but that's only if "processing" means "reading the files". If all you need to do is concat the files, use `sequence`.

If you're going to use parallel, you should really do more than just reading a file into memory.

```javascript
stream.map(file => {
    return _(fs.createReadStream(file))
        .through(doMoreProcessing()) // Only return a small stream.
    })
    .parallel(4);
```

Even if you implement a version of `parallel` that stops buffering after a certain point, you'll basically end up pausing everything except for the first stream until the first stream completes, so there's no real point in doing it.

**Comment by ronag** [comment]
Well, the problem is that when choosing parallelism you always have to take into account the worst case relative to available memory.

If you have a lot of small files (90%) but a few very large files you end up making your parallelism limits based on the few.

**Comment by vqvu** [comment]
My point is that if you attach processing to tour streams *before* doing `parallel` you'll never run out of memory, because all of your data is consumed before it reaches `parallel`, no out of control buffers.

I might be completely missing your point. If so, please post a more concrete usecase.
