### ISSUE TITLE
onErrorResumeNext?

### ISSUE THREAD

**Issue by ronag** [caolan/highland#333]
How would I model `onErrorResumeNext` using highlandjs?

https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/onerrorresumenext.md

**Comment by vqvu** [comment]
```javascript
function doNothing {
}

function onErrorResumeNext(stream) {
    return stream.map(function (s) {
        return s.stopOnError(doNothing);
    }).sequence();
}
```

If your streams already stop on error, you don't even need the `map`. Just `sequence`. In Highland, errors don't terminate a stream like they do in Rx.

**Comment by ronag** [comment]
I dont understand. I want it to continue with another stream if the first stream fails?

**Comment by vqvu** [comment]
That's what it does. Unless by "fail" you mean something other than "emit an error". If you don't want to see the errors, you can filter them out with a

```javascript
stream.map(_.stopOnError(doNothing))
    .sequence()
    .errors(doNothing);
```

`sequence` doesn't stop on errors. Most Highland operators don't.

**Comment by ronag** [comment]
I don't think this quite fits the behaviour I'm looking for:
```
const s1 = _((push) => {
    push(null, 1)
    push(null, 2)
    push(err)
})
const s2 = _((push) => {
  push(null, 3)
  push(null, 4)
})

s1.through(onErrorResumeNext(s2)).each(x => console.log(x))
// => [1, 2, 3, 4]
```

**Comment by ronag** [comment]
I would later want to implement a `retry` on top of this.

**Comment by vqvu** [comment]
Oh, I see. You only want to go to the next stream if you throw an error. That's not what Rx's `onErrorResumeNext` does.

```javascript
var Rx = require('rx');

var o1 = Rx.Observable.return(1);
var o2 = Rx.Observable.return(2);

Rx.Observable.onErrorResumeNext(o1, o2).subscribe(
    function (x) {
        console.log('next: ' + x);
    },
    function (err) {
        console.log('error: ' + err);
    },
    function () {
        console.log('Completed');
    });
// => next: 1
// => next: 2
// => Completed
```

Here's another try based on `stopOnError`.

```javascript
function onErrorResumeNext(s) {
    return function (stream) {
        return stream.consume(function (err, x, push, next) {
            if (err) {
               next(s);
            }
            else if (x === nil) {
                push(null, nil);
            }
            else {
                push(null, x);
                next();
            }
        });
    };
}
```

**Comment by vqvu** [comment]
Implementing `retry` is probably more complicated. You'd probably want something similar to `sequence`.
