### ISSUE TITLE
Website "Download" button points to source with local file paths

### ISSUE THREAD

**Issue by chanced** [caolan/highland#338]
I was just looking through the source via the direct download link on highlandjs.org and noticed that it had local file paths from the build:

The link points here: https://cdn.rawgit.com/caolan/highland/2.5.1/dist/highland.js

```javascript
}).call(this,_dereq_("/home/jwagner/gh-highland/node_modules/browserify/node_modules/insert-module-globals/node_modules/process/browser.js"),typeof self !== "undefined" ? self : typeof window !== "undefined" ? window : {})
},{"./support/isBuffer":9,"/home/jwagner/gh-highland/node_modules/browserify/node_modules/insert-module-globals/node_modules/process/browser.js":7,"inherits":6}]},{},[1])
(1)
});
```

**Comment by quarterto** [comment]
Those file paths are actually just internal references in the Javascript bundle. It's a side-effect of how Browserify bundles things. The first path is the require call, which references the module id pointed to by the second instance of the path. Nothing to worry about, the bundle definitely works :)

---

@vqvu @jeromew I notice we're using a really old version of Browserify, should we think about upgrading?

**Comment by vqvu** [comment]
Yes, but I think we should set up automated testing in browsers first (#239).
