### ISSUE TITLE
toArray doesn't accept a node-style callback function.

### ISSUE THREAD

**Issue by Neppord** [caolan/highland#344]
There are some issues here discussing the need for promises (#55, #290). In one way I agree, though to depend on a promise library is a bad idea. But there is already a universal interface that any promise library worth its name can interface with, enter the node callback function.

You probably already know that the node-style of callbacks looks like this:
```js
function (error, value) {
  if(error !== null) handle_error(error);
  else do_something_with_value(value);
}
```

If we could have a function that takes this style of callback we don't need to argue about what promise lib we wan't or should use.

I would like to suggest a function called `nodestyleToArray` or `nToArray`.

**Comment by quarterto** [comment]
Copying my thoughts from the pull request thread:
> I think the name is slightly misleading. We usually use n_____ for something that consumes a certain number (n) of items. So, looking at the name I expected it to be implemented as .take(n).collect().
>
> As for the method itself, I'm a weak +1. It's not something I'd use myself, but I can see it would be useful.

**Comment by Neppord** [comment]
After writing the pull request and realizing how the function would be implemented this feels unneeded. So i will close this issue.

There is however a need for some improved documentation of `pull` which implements the bulk of what was needed.

Thanks @quarterto for the help!
