### ISSUE TITLE
Parallel consumption of one stream

### ISSUE THREAD

**Issue by justincy** [caolan/highland#36]
How can I have multiple consumers receiving data from one object stream in parallel? `parallel` only works on streams of streams.

**Comment by zoellner** [comment]
Is there any update on this?
My use case:
I have a stream of ids that I map into http requests. I want to process several requests in parallel (since the API I am calling can handle hundreds of requests a second but a single stream only reaches around 50 req/s)

**Comment by vqvu** [comment]
Can't you just use `parallel` or `mergeWithLimit`?

```javascript
ids.map(id => {
    // make request.
    // wrap in stream.
}).mergeWithLimit(numWorkers);
```

**Comment by zoellner** [comment]
Thank you. Exactly what I needed. Didn't have that one on my radar.

**Comment by bradserbu** [comment]
I've used what @vqvu mentions above with success.  However, there are a few specialized use cases where what I actually need/want is a `ids.**flatMap**(id => {`.  

Using the `flatMap` with a highland wrapped promise has the effect of only running one promise at a time.  

The `flatMap` makes a difference when you want to consume a stream of arrays.  Processing each with an activity (promise) that returns an array of results.  Then produce as output, after the merge, a single, flattened, stream of results.  


For performance reasons, doing a `.flatten()` after the merge does not solve the performance problems when processing extremely large amounts of data.  A `.flatten()` after the `.merge()` would accomplish the desired output, but when each array has millions of items each, the `.flatten()` kills performance.

**Comment by jeromew** [comment]
Note that `flatMap(f)` is equivalent to `map(f).sequence()`

what you want is `ids.map(f).parallel(10)` to have 10 promises built by f in parallel.

**Comment by justincy** [comment]
2.5 years later, I'm back to using highland and I still can't figure this issue out. `map(f)`, so far as I can tell, is only useful for synchronous operations. HTTP requests are not synchronous. How do I get a pool of asynchronous HTTP workers consuming from a single stream?

**Comment by svozza** [comment]
The answer is above there, use `map` to convert your stream into a stream of streams and then use `mergeWithLimit`.

```js
_(['www.example.com/foo', 'www.example.com/bar', 'www.example.com/baz'])
    .map(makeHtttpRequest) // this function should return a Highland stream
   .mergeWithLimit(noOfWorkers);
```

**Comment by justincy** [comment]
@svozza Thanks. I don't know why it took so long for me to understand. I was about to write a reply explaining why I can't use map because it requires a synchronous function. Then the solution hit me:

```js
_(['www.example.com/foo', 'www.example.com/bar', 'www.example.com/baz'])
    .map(function(url){
        var s = _();
        makeHttpRequest(url, function(error, response){
           s.write(response);
           s.end();
        });
        return s;
    }) // this function should return a Highland stream
   .mergeWithLimit(noOfWorkers);
```

That appears to be working.

**Comment by svozza** [comment]
Could you not just wrap `makeHttpRequest` using `wrapCallback`?

```js
_(['www.example.com/foo', 'www.example.com/bar', 'www.example.com/baz'])
    .map(function(url){
        return _.wrapCallback(makeHttpRequest)(url);
    })
   .mergeWithLimit(noOfWorkers);
```

Actually, you could make that point free:

```js
_(['www.example.com/foo', 'www.example.com/bar', 'www.example.com/baz'])
    .map(_.wrapCallback(makeHttpRequest))
   .mergeWithLimit(noOfWorkers);
```

Btw, if you're using something like `request` or `superagent` they both return Node streams so you can just wrap them in the Highland constructor:

```js
const request = require('request');

_(['www.example.com/foo', 'www.example.com/bar', 'www.example.com/baz'])
    .map(function(url){
        return _(request({url: url, json: true}));
    })
   .mergeWithLimit(noOfWorkers);
```

**Comment by justincy** [comment]
Thanks for the tip about `wrapCallback()`.

I use request for HTTP requests but it's inside of a module that analyze API responses and just returns an object with data that is later processed.
