### ISSUE TITLE
from node stream to node object stream: JSONstream or similar still needed?

### ISSUE THREAD

**Issue by gebrits** [caolan/highland#362]
Probably a pretty native question so bare with me, but does highland provide functionality to change a normal node stream to a node object stream for further along with all the other stuff to process this further? 

Or do I need some preprocessing step (using JSONStream or something) to do the initial convert from a stream to an object stream?

**Comment by vqvu** [comment]
Highland doesn't provide functionality to change a node stream into an object mode node stream. However, you can wrap a regular node stream in highland just fine. Highland doesn't distinguish between object and non-object mode (all Highland streams can be considered objectMode). You'll end up with a bunch of `String` or `Buffer`, which you can convert to whatever form you need via another processing step.

For example,

```javascript
_(fs.createReadStream('file.json')) // Gives you a stream of Buffers
  .through(JSONStream.parse())      // Parses into JS objects
  ... // Do further processing here
```

**Comment by gebrits** [comment]
Cool. All clear. Thanks
