### ISSUE TITLE
Possible bug found with ratelimit

### ISSUE THREAD

**Issue by bapti** [caolan/highland#365]
Hi, I have the following code which works

```
_( commands )
        .map( _.wrapCallback( retry.attempt ) )
        .parallel( 1 )
        .errors( _.curry( processErrors, errors ) )
        .toArray( _.curry( processResults, done, errors ) )
```

I have tried to swap out `parallel` for `ratelimit` like so

```
_( commands )
        .map( _.wrapCallback(retry.attempt ) )
        .ratelimit( 1, 1000 )
        .errors( _.curry( processErrors, errors ) )
        .toArray( _.curry( processResults, done, errors ) )
```

From what I can see the attempt function never gets called with the command in the second version - am I doing something wrong here?  If I swap out my map for just a `console.log` then the rate limit works fine.

**Comment by bapti** [comment]
Here's a simple example I've put together to show what I mean

```
var _ = require('highland');

var delayedMultiply = function(x, done){
    console.log(x)
    var returnValue = x*2;

    fn = function() {
        done(null, returnValue);
    }

    setTimeout(fn, 500)
}

_( [1,2,3,4] )
    .ratelimit( 1, 1000 )
    .map( _.wrapCallback(delayedMultiply) )
    .errors( function(error){
        console.log(error);
    })
    .toArray( function(items){
        console.log(items)
    })

```

**Comment by bapti** [comment]
And in the process I've figured it out, sorry for wasting your time guys - I must've missed something in the docs, heading there now.

```
_( [1,2,3,4] )
    .ratelimit( 1, 1000 )
    .map( _.wrapCallback(delayedMultiply) )
    .series()  
    .errors( function(error){
        console.log(error);
    })
    .toArray( function(items){
        console.log(items)
    })
```

**Comment by LewisJEllis** [comment]
Sometimes laying it out and simplifying the example is all you need :)

Also, a quick note - be aware of [_.log](http://highlandjs.org/#log). This:
```javascript
.errors(function (error) {
    console.log(error);
}).toArray(function (items) {
    console.log(items)
})
```
is the same as:
```javascript
.errors(_.log)
.toArray(_.log)
```

**Comment by bapti** [comment]
@LewisJEllis That's great, that'll come in handy when I'm running my tests.  Much appreciated!

**Comment by vqvu** [comment]
@bapti, another note:

The transform you're looking for is [flatMap](http://highlandjs.org/#flatMap). It's better to use that than `map(...).series()` or `map(...).sequence()`, since it's more explicit. Functionally, it's equivalent to `map(...).sequence()`.

**Comment by bapti** [comment]
@vqvu Thanks for that, I'll make the change :)
