### ISSUE TITLE
Help - Equivalent to async.parallel ?

### ISSUE THREAD

**Issue by iq-dot** [caolan/highland#370]
Hi all,

I've been a long time user of async and I have been recently told to look at using highlandjs instead as it is more performant.

One of the common things I use is the async.parallel to execute functions in parallel and async.series / async.waterfall occasionally.

I am having hard time trying to figure out the best way to convert this in to highland streams:

```
    async.parallel([
            function1,
            function2,
            function3
        ],
        // success callback after all the above have finished
        function(err) {
            if (err) {
                log.error(err);
            }
        }
    );
```

Any tips appreciated

**Comment by quarterto** [comment]
From the [docs for `nfcall`](http://highlandjs.org/#nfcall):

> This can be used as a control flow shortcut and draws parallels with some control flow functions from async. A few rough correspondences include:
>
> * `.nfcall([]).series()` to `async.series()`
> * `.nfcall([]).parallel(n)` to `async.parallelLimit(n)`
> * `.nfcall(args)` to `async.applyEach(..., args)`
> * `.nfcall(args).series()` to `async.applyEachSeries(..., args)`

**Comment by iq-dot** [comment]
I'm using mongoose and I was trying to see if this works, however I get undefined as the result:

```
	hl([
		Collection1.find().lean().exec,
		Collection2.find().lean().exec

	]).nfcall([])
		.parallel(2)
		.stopOnError(errLogger)
		.toArray(test);

	function test(result, err) {
		console.log(result, err); // prints [undefined, undefined]
	}
```

Perhaps I have misunderstood some concepts?

**Comment by LewisJEllis** [comment]
You'll need to bind the Mongoose model to your query so it has the right context. I generally use mongoose static methods for simplicity, so I would do something like:
```javascript
    hl([
        Collection1.myMethod.bind(Collection1),
        Collection2.myMethod.bind(Collection2)
    ]).nfcall([])
        .parallel(2)
        .stopOnError(errLogger)
        .toArray(test);
```
But now that I think about it, I think this ought to work too (but haven't checked):
```javascript
    hl([
        Collection1.find().lean().exec.bind(Collection1),
        Collection2.find().lean().exec.bind(Collection2)
    ])
```
