### ISSUE TITLE
Question: Creating many streams from a single stream

### ISSUE THREAD

**Issue by bapti** [caolan/highland#376]
Hi, I'm stuggling a bit getting my head around how to do something

I have a stream of data like `[1,2,3,4,5,6,7,8,9]`

I want to split the stream into many streams of length 4 so `[1,2,3,4], [2,3,4,5], [3,4,5,6], [4,5,6,7] ...` etc.  I'm then looking to do an operation on each separate stream.

I've read through the docs twice and I think i'm lacking in experience on how to compose the stream operators to do this :(.

Can anyone help please?
Thanks
Neil

**Comment by svozza** [comment]
Not 100% sure what you mean but do you want to split stream into say batches of 4 and then apply the same operation on those batches?

**Comment by bapti** [comment]
@svozza - exactly right, so take the first batch 1-4 then the next batch 2-5 etc.  Each batch will then have an operation applied against it to give a total or a product for instance.  Finally then return the maximum value.

I'm working on this problem in project euler at the moment https://projecteuler.net/problem=8 - I've been working through them with highland to try and sharpen up my knowledge of streams and functional programming.

**Comment by LewisJEllis** [comment]
A custom consumer to do the batching is probably the easiest way here. Highland has batch methods, but they just do splitting instead of duplication/shifting. You could make it work with a goofy forking scheme where you make 4 forks (or 13 for the problem), but that'd be a bit silly.

```javascript
var _ = require('highland');
var xs = "123456789".split('').map(function (i) { return parseInt(i) });

function makeBatcher(size) {
  var batch = [];
  return function (err, x, push, next) {
    if (err) {
      push(err);
      next();
    } else if (x === _.nil) {
      push(null, x);
    } else {
      batch.push(x);
      if (batch.length === size) {
        push(null, _(batch));
        batch.shift(1);
      }
      next();
    }
  }
}

// note: this is the same as .each(_.each(_.log)), but this way is more clear
_(xs).consume(makeBatcher(4)).each(function (stream) {
  stream.each(_.log);
});
```

Of course, for this problem, it's a lot easier to just keep streams out of the picture:
```javascript
var xs = "123456789".split('').map(function (i) { return parseInt(i) });
var max = 0;

function multiply(a, b) {
    return a * b;
}

for (var i = 0; i < xs.length - 4; i++) {
    max = Math.max(max, xs.slice(i, i + 4).reduce(multiply, 1))
}
console.log(max);
```

**Comment by bapti** [comment]
@LewisJEllis thanks for the help, much appreciated
