### ISSUE TITLE
Question: take items from stream while value is less than a max value

### ISSUE THREAD

**Issue by bapti** [caolan/highland#378]
Hi, I've got a quick quesiton about how to take items from an infinite stream - I'd like to be able to do something like below.

```
_(infiniteNumberGenerator)
  .takeWhile( (count) => {
    return count < max;
  })
  .map(...)
```

Is this supported with the methods or would I have to implement something?  Take does this by using slice.  I could estimate how many i need using some maths but I thought it would be nice just to have a clause that stops the stream after enough has been pulled.  Is this doable?

Thanks
Neil

**Comment by bapti** [comment]
Sorry, figured it out

```
var takeWhile = function (f) {
  return (err, x, push, next) => {
    if (err) {
      // pass errors along the stream and consume next value
      push(err);
      next();
    }
    else if (x === _.nil) {
      // pass nil (end event) along the stream
      push(null, x);
    }
    else {
      // pass on the value only if the value passes the predicate
      if (f(x)) {
        push(null, x);
        next();
      } else {
        push(null, _.nil)
      }
    }
  }
}
```

paired with 

```
.consume(takeWhile((x) => {
      return x < max
    }))
```

**Comment by LewisJEllis** [comment]
Glad you worked this out, and with pure highland you're spot on what you're looking for. One note to be aware of - transducer support was added in https://github.com/caolan/highland/pull/223 and `takeWhile` is available as a transducer (see also https://github.com/cognitect-labs/transducers-js), so you can use that to avoid writing your own `takeWhile` implementation if you so prefer.

**Comment by bapti** [comment]
@LewisJEllis - is this something that you'd like as a pull request for highland?  Happy to add it with tests.

**Comment by LewisJEllis** [comment]
Probably not now, but almost definitely after 3.0 and the module system. We try to keep the core lib from becoming a 'kitchen sink', but `takeWhile` could easily fit in a module after 3.0. For now, we access the kitchen sink via transducers.

**Comment by bapti** [comment]
@LewisJEllis thanks for that, is there a ballpark for the 3.0 release?

**Comment by quarterto** [comment]
Soon™ :wink:

Not committing to anything here, but possibly some time in the next 6 months?

**Comment by mauriciocap** [comment]
PR with takeWhile #677 , thanks!
