### ISSUE TITLE
Enable Greenkeeper?

### ISSUE THREAD

**Issue by quarterto** [caolan/highland#386]
We've had a few outdated dependencies recently (#384, #385). Enabling [Greenkeeper](http://greenkeeper.io/) would keep them up to date automatically. We'd need @caolan to enable it because it requires repo hooks. What do we think?

**Comment by vqvu** [comment]
+1 from me.

**Comment by caolan** [comment]
Greenkeeper should now be enabled on this repository... let me know if you notice any issues

**Comment by svozza** [comment]
:+1:
