### ISSUE TITLE
flatMap implies sequence but why?

### ISSUE THREAD

**Issue by gunar** [caolan/highland#399]
flatMap implies sync, whereas from the [docs](http://highlandjs.org/#flatMap) I expected it to be equal to `.map.merge` (instead of `.map.sequence`). Shouldn't it be called sequenceMap or something?

Actually, at first I though `flatMap` meant `.merge.map` i.e. merge a stream of streams and then map the output.

Thank you for this awesome piece of software! :grinning:

**Comment by vqvu** [comment]
The category-theoretic answer is that `flatMap` is the name often given to the [bind operation of a monad](https://en.wikipedia.org/wiki/Monad_%28functional_programming%29#Formal_definition), and `bind` does not reorder :smile:. Highland streams are a monad if you don't consider infinite streams.

The practical reasons are

1. Highland is basically arrays+lazy+async, and if you were to implement `flatMap` on arrays, you would preserve the order.
2. A use-case for highland is the sequencing of asynchronous side-effects, where you care more about correct ordering than throughput.
3. Laziness is an important part of Highland, and `merge` is only partly lazy in the current implementation; it's possible for `merge` to immediately consume the entire source stream and kick off lots of async computations immediately. For example, this code will immediately read from all provided files as soon as you start consuming the stream.

    ```javascript
    // As soon as you call resume or each or any consume method, all of these files will
    // immediately be read.
    _(["a.json", "b.json", "c.json"]).map(_.wrapCallback(fs.readFile)).merge();
    ```

    If you want to opt-out of laziness, you should do it explicitly. `flatMap` is too common of an operation to opt-out by default.

    It's about a matter of priority. If you're familiar with RxJS, they care more about throughput, so their `flatMap` is equivalent to `.map.merge`, and they provide a separate `concatMap` (which is `.map.sequence`).

Let me add that `flatMap` doesn't imply sync. It *does* imply that only one async operation will be executing at the same time. But the operation itself is still executed asynchronously.

I'll update the docs to explicitly mention that `flatMap` is equivalent to `.map.sequence`.

**Comment by gunar** [comment]
@vqvu, thank you very much for your thorough answer.

The *practical reasons* you present here are most reasonable. I see now I have this strange POV on the issue because of the "wierd" nature of the software I'm working atm, i.e. I'm not yet sure Reactive Programming makes solving my problem easier.

Furthermore, I'll try and learn what a Monad is once and for all :smile:

**Comment by vqvu** [comment]
Cool. Feel free to open another issue if you need help figuring out whether or not Highland is a good fit.
