### ISSUE TITLE
Concatenating streams forked from the same source doesn't resume

### ISSUE THREAD

**Issue by theefer** [caolan/highland#40]
I'm working on a highland stream based system for processing asset transformation pipelines. The resulting structure can result in a graph, where a source stream may be `fork`ed, processed differently in parallel, and merged back together using `concat`.

Here is a reduced test case:

```
var s = _([1,2]);

var o1 = s.fork().map(function(x){ return x * 2; });
var o2 = s.fork().map(function(x){ return x * 3; });

var out = o1.concat(o2);

out.each(function(x) {
  console.log(x);
});
```

Which I would have expected should be (more or less) equivalent to:

```
var o1 = _([1,2]).map(function(x){ return x * 2; });
var o2 = _([1,2]).map(function(x){ return x * 3; });

var out = o1.concat(o2);

out.each(function(x) {
  console.log(x);
});
```

This second example outputs "2 4 3 6" as expected, but the first one doesn't output anything.

Is this a bug, or am I missing something?

**Comment by RReverser** [comment]
Just struggled with this too, but upgraded to highland 3.0.0-beta.5, and things seem to work automagically even without `.resume` etc., awesome!

**Comment by vqvu** [comment]
There's nothing about the 3.x code that lets you concat forks. Are you trying to do something slightly different? Because I tried the original test case in this issue, and it definitely doesn't work.

**Comment by RReverser** [comment]
Hmm you're right, it's not the same issue - my was just that forked stream B, appended to the end of another one A, didn't properly resume - data was truncated at the of A despite manipulations with `.fork` / `.observe` / `.resume`, but now somehow works without any changes or tricks.
