### ISSUE TITLE
Can't wrapCallback in self referencing module

### ISSUE THREAD

**Issue by gunar** [caolan/highland#401]
I looked for an answer in issues involving `wrapCallback` - e.g. 334, 246, 296 - but couldn't resolve this.

[Node-twitter](/desmondmorris/node-twitter) is callback-oriented

```js
client.get('statuses/user_timeline', params, function(error, tweets, response){
  if (!error) {
    console.log(tweets);
  }
});
```

Hence, I tried

```js
var _ = require('highland'),
   Twitter = require('twitter');

var client = new Twitter({ /* secret API keys */ });
var get = _.wrapCallback(client.get);

get('application/rate_limit_status', { resources: 'favorites' }).apply(function (d) {
  console.log(d);
});
```

which throws

```js
./node_modules/twitter/lib/twitter.js:167
  return this.__request('get', url, params, callback);
              ^

TypeError: this.__request is not a function
    at Twitter.get (./node_modules/twitter/lib/twitter.js:167:15)
```

---

I've had no success trying
- `streamifyAll`
- `_([client]).invoke()`
- `return _.(function (push, next) { ... } )`
- nor currying the function before/after wrapCallback (I had to try, right?).

Using `_(Q.ninvoke(client, 'get', '', {}).then(function (data) { return data[0]; }))` works, though. But I don't want to depend on Q, if that's possible.

BTW, Twitter-node defines `get()` as

```js
Twitter.prototype.get = function(url, params, callback) {
  return this.__request('get', url, params, callback);
};
```

Thank you all very much for your time.

**Comment by jeromew** [comment]
I am not saying it will make things work, but your first error makes me think you should try

    var get = _.wrapCallback(client.get.bind(this));

instead of

    var get = _.wrapCallback(client.get);

**Comment by gunar** [comment]
@jeromew Thank you but no, I still get `TypeError: this.__request is not a function` 😕

**Comment by jeromew** [comment]
did you try with `client.get.bind(client)`or client.get.bind(this)` (I made an error in my first comment that I edited afterwards)

**Comment by gunar** [comment]
`client.get.bind(client)` worked. Thank you very much, @jeromew .

It's very unfortunate that Github live-updates to show new comments, but doesn't do the same for edits.

I understand this issue has everything to do with knowing JS itself and less so with Highland.js, so really, thank you.
