### ISSUE TITLE
Release new highland version

### ISSUE THREAD

**Issue by jgrund** [caolan/highland#419]
There have been a number of commits since 2.5.1 including some bug fixes. I know 3.x is around the corner but it would be useful to cut another 2.x release.

**Comment by wayneseymour** [comment]
I for one, can definetly use a new cut.
I have the problem that [this pr](https://github.com/caolan/highland/pull/367/files) fixes.

I can't ship without this.  :-1:

**Comment by svozza** [comment]
Yes, we need a release soon. I've actually just been running off `master` in production for the past few weeks. I'll  put together the changelog  tomorrow if I get a chance.

**Comment by wayneseymour** [comment]
Thanks a bunch!

**Comment by vqvu** [comment]
@svozza I have a partial changelog I was working on a few weeks ago (https://github.com/vqvu/highland/blob/2.6.0-changelog/CHANGELOG.md) if you want a starting point.

**Comment by wayneseymour** [comment]
Sweet

**Comment by wayneseymour** [comment]
Will this issue make it into 2.6.0? 2.6.x?  :smiling_imp:

**Comment by wayneseymour** [comment]
Woohoo!  Excited! 
Thanks again

**Comment by svozza** [comment]
Sorry it's taken me so long, Christmas et al got in the way! Let me know if I've missed anything.

**Comment by jeromew** [comment]
2.6.0 is released. Thanks again @svozza for the changelog. We should probably require that the changelog be updated every time a new feature is added so that it is always release-ready

**Comment by svozza** [comment]
Yep, good point, I'll add it to `Contributing.md`. Thanks for getting the release out! :smile:

**Comment by jeromew** [comment]
They were 2 deprecation warning in the tests

Highland: Calling Stream.fork() on a stream that has already been consumed is deprecated. Always call fork() on a stream that is meant to be forked.

Highland: Calling Stream.map() with a non-function argument is deprecated.

I did not modify the test cases as we might want to continue testing deprecated features until removed.
