### ISSUE TITLE
Parallel bug

### ISSUE THREAD

**Issue by mlconnor** [caolan/highland#420]
Running 2.5.1 of highland but I also tried this with git://github.com/s3u/JSONPath#d01c16201cdbbb600ffd914192b0a307ad00c66c

The following script works as expected.  I get an array with three file buffers printed to the console.

    _ = require('highland');

    _(['testreq.js', 'testcert.coffee', 'tmpcert.pem'])
      .map(_.wrapCallback(require('fs').readFile))
      .series()
      .toArray(function(v) {
	console.log(v);
      });

But when I run the same thing in parallel nothing is printed.

    _ = require('highland');

    _(['testreq.js', 'testcert.coffee', 'tmpcert.pem'])
      .map(_.wrapCallback(require('fs').readFile))
      .parallel()
      .toArray(function(v) {
	console.log(v);
      });

I've also tried this with each and it never seems to be called.  Any thoughts?  I've also tried this with a simple timeout function and same result.

**Comment by svozza** [comment]
Is that `parallel` right? You need to pass in a number to that function. Also, is there a reason you're using `parallel` rather than `merge`?

**Comment by mlconnor** [comment]
bone headed move on my part.  merge is the function i needed, thanks @svozza

**Comment by svozza** [comment]
In wondering if we should throw if not supplied an integer to `parallel `.

**Comment by mlconnor** [comment]
that would be nice. in general, checking methods for correct parameters is helpful.  highland is a rush when it's working but it's tough to debug when it's not.

**Comment by vqvu** [comment]
@mlconnor #421.
