### ISSUE TITLE
Not quite getting `node-feedparser` Node Stream to work

### ISSUE THREAD

**Issue by floringogianu** [caolan/highland#424]
I am trying to use a node module that is working with node `Stream` in the browser, using Highland. https://github.com/danmactough/node-feedparser is the module in cause.

```javascript
import {ajax, get} from "jquery";
import _ from "highland";
import feedParser from "feedparser";

var author = 'Jaderberg_M';
var url = 'http://export.arxiv.org/api/query?search_query=au:' + author;

// Create a feedParser Stream (a Node Stream)
var parseStream = new feedParser();

// Convert jQuery Promise to a HighlandStream
var reqStream = _(get(url));

// Attempting to parse the request
reqStream
  .pipe(parseStream);
```

Supposedly now I should be able to do something with the `parseStream` in order to read from it the parsed XML but any consumption method I tried (`.each`, `.pull`) didn't allow me to iterate through the stream and check if it actually parsed the incoming XML. Any suggestions on what I am doing wrong? 

Thanks!

**Comment by vqvu** [comment]
`parseStream` is a Node stream. It doesn't have `each` and `pull`. You could use [on('data', ...)](https://nodejs.org/api/stream.html#stream_event_data) to get the parsed XML out. Alternatively, use [through](http://highlandjs.org/#through) rather than `pipe` to get back a Highland stream that *does* have `each` and `pull`.

**Comment by floringogianu** [comment]
@vqvu thanks. I tried with through also but didn't mention it because I thought I was off using the library anyway :)

```javascript
reqStream
  .through(parseStream)
  //.errors(err => console.log(err))
  .each(x => console.log(x));
```

However I get this:  `Uncaught TypeError: Invalid non-string/buffer chunk`. I guess `FeedParser` doesn't play nice with the Highland stream... I can't use `on('data', ...)` because I am in a browser...

**Comment by jeromew** [comment]
Did you check to see if `get` actually gets something. I did not check the CORS settings of arxiv but what you are doing is a cross-domain ajax call which is usually not valid (is there an error message in the browser console ?)

**Comment by floringogianu** [comment]
Yes, `get` works fine. Actually if I wrap `parseStream` in a Highland stream as below I get the entire xml document in the console, but that's not really helpful, nothing is actually being parsed.

```javascript
reqStream
  .pipe(_(parseStream))
  .each(x => console.log(x))
```

**Comment by jeromew** [comment]
could you build a jsfiddle that we could tinker with ?

it should work with through

what is the output of

reqStream
  .each(x => typeof x);

I suspect that jquery gives you an XML root element according to 

> The success callback function is passed the returned data, which will be an XML root element, text string, JavaScript file, or JSON object, depending on the MIME type of the response. It is also passed the text status of the response.

and the API gives

> Content-Type:application/atom+xml; charset=UTF-8

**Comment by floringogianu** [comment]
I was going to create a jsfiddle or a jsbin but `node-feedparse` was not include-friendly. I found however this nice requireBin that allows you to load node-modules: http://requirebin.com/embed?gist=6264704

**Comment by vqvu** [comment]
`Invalid non-string/buffer chunk` means you're pushing a non-string/Buffer object through `parseStream`, and it is not in `objectMode`.

I just did 

```javascript
$.get('http://export.arxiv.org/api/query?search_query=au:Jaderberg_M')
    .then(a => console.log(typeof a))
// => object
```

and got an `XMLDocument` out, so @jeromew is right. If you want to use `feedparse`, you'll need to tell jQuery not to parse the result using the `dataType` argument.

> dataType
> Type: String
> The type of data expected from the server. Default: Intelligent Guess (xml, json, script, or html).

```javascript
$.get('http://export.arxiv.org/api/query?search_query=au:Jaderberg_M', null, null, 'text')
    .then(a => console.log(typeof a))
// => string
```

**Comment by floringogianu** [comment]
@vqvu , @jeromew Thank you for your support, much appreciated! Indeed I was not paying attention at the type `.get` was returning. Works like a charm now.
