### ISSUE TITLE
Unable to reuse the pipeline definition

### ISSUE THREAD

**Issue by GolfRider** [caolan/highland#430]
Hi , 

I didn't find anywhere in the doc on how to re-use the pipeline.
For eg:
 var h=_([data])
 var stage1=  _.pipeline(h.flatMap(h.wrapCallback(function1),
                                      h.flatMap(h.wrapCallback(function2))
 var stage2=  _.pipeline(h.flatMap(h.wrapCallback(function3),
                                      h.flatMap(h.wrapCallback(function4))

         h.pipe(stage1).
            pipe(stage2).
            pipe(stage1).  // If stage1 is re-used again, it says you can't use an already consumed 
                                 //stream, you may need to fork/observe   
            stopOnError().each();

As a workaround , I have defined stage3 whose pipeline definition is same as stage1.

Please let me know if there is a better way.
Thanks

**Comment by vqvu** [comment]
You can't reuse pipelines. The `pipeline` method returns Highland through stream that, like all other Highland streams is one-time use.

If you want a custom transformation pipeline, use `seq

**Comment by vqvu** [comment]
You can't reuse pipelines. The `pipeline` method returns Highland through stream that, like all other Highland streams is one-time use.

If you want a custom transformation pipeline, use `seq` and `through`.

```javascript
var h=_([data])

var stage1 = _.seq(
    _.flatMap(_.wrapCallback(function1)),
    _.flatMap(_.wrapCallback(function2)))

var stage2 = _.seq(
    _.flatMap(_.wrapCallback(function3)),
    _.flatMap(_.wrapCallback(function4)))

h.through(stage1)
    .through(stage2)
    .through(stage1)
    ...
```

Note: Previous incomplete response was accidentally submitted.

**Comment by GolfRider** [comment]
Thanks Victor, that works...!!
