### ISSUE TITLE
Question: What's left before 3.0 release?

### ISSUE THREAD

**Issue by dmfenton** [caolan/highland#440]
I have a module that depends pretty heavily on pipelines. I'm willing to swap in the 3.0 branch and see how it runs but I'm curious as to your plans for releasing that branch. I'd appreciate any info.

Thanks and keep up the great work!

**Comment by quarterto** [comment]
There is a checklist in #179, not sure if it's up to date. I think "all" that's left is some more enthusiasm from us contributors.

**Comment by dmfenton** [comment]
Thanks @quarterto that's awesome! I've already dropped the 3.0 branch into github.com/koopjs/geoxform and all my tests have passed. I'm going to be running some heavy integration tests later today. I'll post any Highland related issues (if I find any).

**Comment by dmfenton** [comment]
The 3.0 branch gave me a huge performance upgrade and I didn't find any bugs in my testing. Looking forward to the official release!
