### ISSUE TITLE
Keep destination open when pipe source finishes with error

### ISSUE THREAD

**Issue by ronag** [caolan/highland#441]
Please help me get out of this pattern with expressjs.

Basically what I need to do is to keep the `res` stream open if I want another middleware to try an serve it:

```javascript

function serve(dir) {
  return (req, res, next) => {
      let finished = true

      // tail.createReadStream returns a highland stream
      tail
        .createReadStream(path.join(dir, req.params.fileId))
        .on('error', err => {
          finished = false
          if (err.code === 'ENOENT') {
            next()
          } else {
            next(err)
          }
        })
        .pipe(new PassThrough())
        .on('end', () => {
          if (finished) {
            res.end()
          }
        })
        .pipe(res, { end: false })
  }
}

app.get('/:fileId', [
  serve('foo'),
  serve('bar'),
])
```

There has to be a better way? I hope...

**Comment by ronag** [comment]
I kind of need a `readable` event...

**Comment by jeromew** [comment]
I don't understand what you are trying to do. `serve('foo')` creates a stream A, `serve('bar')` creates a stream B, and you want to first fully flush A on res and then flush B ?

**Comment by ronag** [comment]
@jeromew: No, if `serve('foo')` a doesn't find the file it should allow `serve('bar')` to try...

**Comment by ronag** [comment]
It feels like I am missing something fundamental but without this weirdness I cannot get it to work.

**Comment by ronag** [comment]
I guess this is why AWS uses `readable` in their `s3.upload` implementation (https://github.com/caolan/highland/issues/431)

**Comment by jeromew** [comment]
The problem I think is that once a stream is piped (be it a highland stream or a node stream), if it ends or errors, it will close res except, as you did, if it has { end: false }

Dynamic reconfiguration of a stream network (foo=>res becomes bar=>res) is not easy to abstract. It could be possible with highland but my first reaction would be to direct you to https://www.npmjs.com/package/stream-splicer ; I understand it could solve your problem (but have not tried it myself in the pattern you describe)

**Comment by ronag** [comment]
@jeromew: How about something like:

```javascript
tail
  .createReadStream(path.join(dir, req.params.fileId))
  .on('readable', (stream) => {
     steam.pipe(res)
   })
   .on('error', err => {
      if (err.code === 'ENOENT' && !this.readable) {
        next()
      } else {
         next(err)
      }
 })
```

**Comment by jeromew** [comment]
From my understanding, there is no real reason that anything starts upstream until "stream.pipe(res)" is called.

For a simpler alternative in your specific case, can't you check if `path.join(dir, req.params.fileId)` exists with `fs.stat` before dealing with highland/streams ?

**Comment by ronag** [comment]
> For a simpler alternative in your specific case, can't you check if path.join(dir, req.params.fileId) exists with fs.stat before dealing with highland/streams ?

No I can't, the file might be delete between `fs.exists` and `fs.createReadStream`.

How about a helper function? Something like?

```javascript
function fallback(src, dst, filter, next) {
  let finished = true

  src
    .on('error', err => {
      finished = false
      if (filter(err)) {
        next()
      } else {
        next(err)
      }
    })
    .pipe(new PassThrough())
    .pause()
    .on('end', () => {
      if (finished) {
        dst.end()
      }
    })
    .pipe(dst, { end: false })
}
```

**Comment by jeromew** [comment]
you could maybe use `fs.open` to get the file descriptor and then createReadStream with the file descriptor to avoid the case of the disappearing file.

The helper function could work but what I don't understand is that with this method you can only have a clean result with a very early error (like "file does not exist"). If piping has started, the res will be dirty before the second file gets piped.

I don't really understand (I am sorry I may be missing something) if this is a highland issue or a more generic stream fallback issue ?

**Comment by ronag** [comment]
This should only happen with early errors.

>I don't really understand (I am sorry I may be missing something) if this is a highland issue or a more generic stream fallback issue ?

I'm not sure myself.

**Comment by ronag** [comment]
Ok, so the general pattern for this is as follow:

```javascript
      let end = true
      fs.createReadStream(path)
        .on('error', err => {
          if (err.code === 'ENOENT') {
            end = false
            next()
          } else {
            next(err)
          }
        })
        .pipe(new PassThrough())
        .on('end', () => {
          if (end) {
            res.end()
          }
        })
        .pipe(res, { end: false })
```

As long as this is the most pragmatic and correct way to do this I'm happy with it.

**Comment by ronag** [comment]
@jeromew: What I don't understand though is why I have to use `PassThrough` for this to work?

**Comment by vqvu** [comment]
> What I don't understand though is why I have to use PassThrough for this to work?

Highland's `pipe` doesn't support  the optional `{ end: false }` argument. Is that your problem?

Regarding your main question. A generic `pipeIfNoError` operator is tricky to implement in both highland and node streams. However, in the case where the error must come at the start (as with `ENOENT`), you can do an initial `pull` and make your decision when that produces a value, which has the benefit of less state juggling.

```javascript

var next = function (err) {
    console.log('next', err);
}

var s = _(fs.createReadStream('not exist'))
    .stopOnError((err, push) => push(err));

s.pull((err, x) => {
    if (err) {
        if (err.code === 'ENOENT') {
            next();
        } else {
            next(err);
        }
    } else if (x === _.nil) {
        res.end();
    } else {
        res.write(x);
        s.pipe(res);
    }
})

// => next undefined
```

For the specific case of reading from a file, though, @jeromew's suggestion to use `fs.open` is probably the cleanest way.

**Comment by ronag** [comment]
> For the specific case of reading from a file, though, @jeromew's suggestion to use fs.open is probably the cleanest way.

Yes, but I want to do the same thing for http requests that respond 404.

**Comment by ronag** [comment]
So something like

```javascript
fallback(s, filter) {
  s.stopOnError((err, push) => push(err))
  s.pull((err, x) => {
    if (err) {
        if (filter(err)) {
            next()
        } else {
            next(err)
        }
    } else if (x === _.nil) {
        res.end()
    } else {
        res.write(x)
        s.pipe(res)
    }
})
}
```

**Comment by ronag** [comment]
> A generic pipeIfNoError operator is tricky to implement in both highland and node streams.

A version of `otherwise` that also continues on error would be enough?

**Comment by vqvu** [comment]
> So something like
> 
> &lt;snip&gt;

Yeah, I think that should work.

> A version of otherwise that also switches when there is an error + no previous data would be enough?

Maybe, but when I say "generic `pipeIfNoError`", I meant it should handle the case where there is previous data before the error. That's the tricky part.

The code that you posted though, may not work, since you still have to pipe if the `otherwise` did not switch, and there no way to detect that with `otherwise`.
