### ISSUE TITLE
How to unpipe if destination is closed?

### ISSUE THREAD

**Issue by ronag** [caolan/highland#442]
```javascript
const p = spawn(....)
stream
  .pipe(p)
p.kill()
// EPIPE
```

**Comment by vqvu** [comment]
We don't have a proper `unpipe`, but `destroy` seems to work in lieu of that.

```javascript
const _ = require('highland');
const spawn = require('child_process').spawn;

var s = _(function (push, next) {
    setTimeout(() => {
        console.log('write');
        push(null, '1\n');
        next();
    }, 1000);
});

var p = spawn('cat');

p.stdout.pipe(process.stdout);

p.on('close', () => s.destroy());

s.pipe(p.stdin);

setTimeout(() => p.kill(), 3500);
```

**Comment by ronag** [comment]
@vqvu Is `close` an undocumented feature? I can't find it here https://nodejs.org/api/process.html

**Comment by vqvu** [comment]
`close` is documented here: https://nodejs.org/api/child_process.html#child_process_class_childprocess

Anyway, I didn't read the docs closely enough. Looks like you actually want [`exit`](https://nodejs.org/api/child_process.html#child_process_event_exit) instead of close.
