### ISSUE TITLE
Fork/Merge Question

### ISSUE THREAD

**Issue by oravecz** [caolan/highland#451]
I have a fairly simple fork/merge test. After forking the stream and applying some processing, I attempt to merge the streams together so I can trigger the `done()` method. At the moment, the `done()` method is not invoked. I notice that the order matters somewhat. if I put the merge before the even/odd stream processing, the merge and done methods occur.

Is the problem caused by the fact that the streams are basically consumed by the `each()` methods and there is no more data in the streams to trigger the merge? If so, what alternatives do I have to approach the problem?

```js
var h      = require( 'highland' );

describe( 'highland test', function () {

    function isEven( value ) {
        return value % 2 == 0;
    }

    function log( prefix ) {
        return function ( message ) {
            console.log( prefix + ':' + message );
        }
    }

    it( 'fork/merge test', function ( done ) {
        var a = h( [1, 2, 3, 4, 5, 6, 7, 8, 9] );

        var even = a.fork().filter( isEven );
        var odd  = a.fork().reject( isEven );

        even.each( log( 'even' ) );
        odd.each( log( 'odd' ) );

        h( [even, odd] ).merge().done( done );
    } );
}
```

**Comment by vqvu** [comment]
> Is the problem caused by the fact that the streams are basically consumed by the each() methods and there is no more data in the streams to trigger the merge?

Exactly. You already consume from `even` and `odd` when you call `each`, so you can't use them again. In general, Highland streams are one-time-use. This is true of almost all operators, not just `each`. The fact that it works when you move the `merge` to before the processing is probably a happy coincidence.

```javascript
// Even though map is lazy and doesn't consume from the stream immediately, it
// will eventually when you call one of the consumption operators.
// You can't use these streams any more.
even.map(...);
odd.map(...);

// This will throw.
even.map(somethingElse);

// This won't throw immediately because of laziness, but you still can't do it, and
// it may throw later.
h( [even, odd] ).merge().done( done );
```

The code tries to detect this double use as best as it can, but it can't always do it reliably. Regardless, you shouldn't do it as you'll get unpredictable behavior.

If you want to consume from the same stream multiple times, you need to use `observe` or `fork`. In this case, you can `observe` the streams if you want to log them.

```javascript
even.observe().each( log( 'even' ) );
odd.observe().each( log( 'odd' ) );

h( [even, odd] ).merge().done( done );
```

`observe` passively watches the streams, so nothing will get logged until you consume from them with the call to `done`. At that point, data should be logged as soon as it is emitted.

If you're doing some processing that doesn't involve a [consumption operator](http://highlandjs.org/#Consumption) (e.g., `map`), you can merge the processed streams instead.

```javascript
h( [
  even.map(...),
  odd.map(...)
] ).merge().done( done );
```

**Comment by oravecz** [comment]
Great information. Thanks.
