### ISSUE TITLE
can't listen to stream event

### ISSUE THREAD

**Issue by namlook** [caolan/highland#456]
I have an issue when trying to listen to the stream event. In the following example, the response is **not displayed**:

```javascript
_.(request.get('http://www.google.com'))
    .on('response', function(response) {console.log(response);})
    .pipe(process.stdout)
```

however, without highland, the response **is printed**:

```javascript
request.get('http://www.google.com')
    .on('response', function(response) {console.log(response);})
    .pipe(process.stdout)
```

Is it a normal behavior or a bug ? How can I listen to the `response` event with highland ?

PS: using highland 2.6.0 on nodejs 4.2.6

**Comment by quarterto** [comment]
> How can I listen to the response event with highland ?

The short answer is you can't. Highland doesn't forward events from streams. You'd have to listen to it separately:

```js
var res = request.get('http://www.google.com');
res.on('response', function(response) {console.log(response);});
_(res)
    .pipe(process.stdout);
```

**Comment by namlook** [comment]
This is unfortunate as I have to use event-stream instead. Indeed, I need to access the `response` event downstream but need to perform some computation upstream...

Would it be possible to implement a function that would tell highland to listen some events ? Something like this:

```javascript
// upstream
var getStream(url) {
    return _(request.get(url)).listenTo(['response', 'otherEvent').map(someFunc);
}

// downstream

var stream = getStream('http://google.com');
stream.on('response', function(response) {
   console.log(response.statusCode);
});
```

**Comment by vqvu** [comment]
> Would it be possible to implement a function that would tell highland to listen some events ?

Not without a significant rewrite of the Highland core, as it wasn't written to be an arbitrary events forwarder. You'd have to figure out how such custom events would interact with backpressure and laziness.

That's not to say you can't do something manually to get what you want. Just that the `listenTo` operator as you've described it is not really possible.

```javascript
// upstream
function getStream(url) {
    var requestStream = request.get(url);
    var s = _(requestStream).listenTo(['response', 'otherEvent').map(someFunc);
    requestStream.on('response', function (response) {
        // Manually forward the event.
        s.emit('response', response);
    });
    return s;
}

// downstream

var stream = getStream('http://google.com');
stream.on('response', function(response) {
   console.log(response.statusCode);
});
```

What you *can't* do

```javascript
getStream('http://google.com')
    .map(...)
    .on('response', function (response) {
        // Won't get called.
    });
```

**Comment by namlook** [comment]
Thank you for this detailed answer. I guess it is better to use highland the latest as possible to be able to use regular stream features upstream...

I will close this ticket for now. Feel free to reopen it if you think it worth to mention this issue in the documentation.
