### ISSUE TITLE
consume stream from .map() ?

### ISSUE THREAD

**Issue by psi-4ward** [caolan/highland#457]
```javascript
import HL from 'highland';
let files = ['a','b'];

    HL(files)
      .map(file => {
        let s = request(file).pipe(request.put({
          url: 'http://myserivce',
          headers: { 'Accept': 'text/plain' }
        }));
        return HL(s);
      })
      .series()
      .each(res => console.log(res); );
```

I'll never reach the `.each` func, do i anything wrong here?

**Comment by vqvu** [comment]
Is `request.put` also a Readable or just a `Writable`? If it's just a `Writable`, you can't wrap it in a Highland stream. See the discussion in #444 for how to get around that.

**Comment by psi-4ward** [comment]
It should be a also a Writeable stream.
I did some refactoring and it works now but i couldnt find out why.
Thanks anyway!
