### ISSUE TITLE
Release a 3.0 alpha/beta

### ISSUE THREAD

**Issue by dmfenton** [caolan/highland#458]
From an outsider's perspective, the 3.0 branch is excellent. It's got huge performance gains for pipeline, and I haven't run into a single bug yet.

It would be really nice if I could point my package.json at 3.0 rather than commit shas. That would help me keep up with bug fixes on the 3.0 branch. 

Just a thought, I won't be offended at all if the maintainers disagree!

**Comment by quarterto** [comment]
We've mooted this before, and I think it's a great idea. I don't have npm access though; I think it's @vqvu and @jeromew that do. You *can* use 3.0 right now in package.json by pointing straight at the git repository with `npm install --save caolan/highland#3.0.0` (of course, this is prone to breakage, so you might want to lock to a commit with `npm install caolan/highland#b24396f1`).

**Comment by dmfenton** [comment]
>  so you might want to lock to a commit with npm install caolan/highland#b24396f1

That's what I'm doing now. However, that means I have to evaluate the project every time I want to update. I'd prefer to trust the maintainers to make releases and follow those.

**Comment by jeromew** [comment]
@quarterto, @vqvu, @caolan I am not against releasing 3.0 as some preview version (with @next or @3.0.0), but would like to have your opinion first on another option that I think could be interesting for the future of the project :
 - create a "highland-core" project under the highlandjs organisation (or under caolan's repo?). This would have the highland 3.0 engine, but stripped out of unnecessary cruft and transforms (@quaterto has already mentioned several times and I agree that there are too many transforms in highland that belong to plugins)
 - then release a new "highland" version in this repo that would be like a highland-core + a set of plugins that would match the current feature set of highland

**Comment by quarterto** [comment]
I definitely think that's the direction we should take for future releases, but I don't think we should do it for 3.0. We risk users having to make too much of a jump between major versions.

**Comment by vqvu** [comment]
@jeromew, I agree with everything that you've said.

@quarterto It shouldn't be any bigger change than what we're asking users to do now. `npm install highland` should still install the version of highland with all current transforms. My understanding is that there'll just also be a `highland-core` that contains fewer transtorms and one or more `highland-*` packages that contain other transforms. I agree that we'll want to maintain the `highland` package for a while and definitely for the proper 3.0.0 release.

@caolan I would also like your opinion on the proposal to put these repos under the highlandjs organization. If nothing else, it'll let me @ mention the whole highland team, which I've wanted to do many times :smile:.

@dmfenton I've released `3.0.0-beta.1` to npm. It's a beta release, so the website hasn't been updated, but you can get the docs [here](https://github.com/caolan/highland/tree/3.0.0-beta.1/docs). It's just a static site. Please let us know if there are any issues.

**Comment by vqvu** [comment]
I also released `2.7.1` while I was at it. It contains the fix to `pipe`. @ronag, FYI...

It's `2.7.1` because I screwed up the `2.7.0` release in npm.

**Comment by dmfenton** [comment]
Thanks to all of you guys! And thank you @vqvu for releasing 3.0. From my perspective, this issue can be closed. I'll leave it open for you guys if you want to discuss further.
