### ISSUE TITLE
Highland + net sockets

### ISSUE THREAD

**Issue by nicwsm** [caolan/highland#470]
Hi,

I'm trying to use highland.js together with net servers. So the scenario is that I have a server, and that I have two clients connected to it on a separate port, let's say 7001 and 7002. On one end, when I first received a data, I converted it into a highland stream --> stream1 = h(socket). On the other, I did the same thing --> stream2 = h(socket). But on top of that, I also piped the two together:

```
net.createServer(function(socket) {
    stream1 = h(socket);
}).listen(7001)

net.createServer(function(socket) {
     stream2 = h(socket);
     stream1.pipe(stream2)
}).listen(7002)
```

But at the end I realise that stream2 cannot receive any data from stream1 at all, but if I pipe stream1, I can see it on my server console.log. 

Please help. Thanks.

**Comment by vqvu** [comment]
You can't pipe Highland streams in this way. The only Highland stream that you can pipe to are those constructed using the null constructor (i.e., `_()`) or `pipeline`. Most highland streams are read-only.

You can try to pipe to the socket directly. Something like this should work.

```javascript
net.createServer(function(socket) {
    stream1 = h(socket);
}).listen(7001)

net.createServer(function(socket) {
     stream2 = h(socket);
     stream1.pipe(socket)
}).listen(7002)
```

**Comment by benjaminhon** [comment]
cool

**Comment by nicwsm** [comment]
It works! Thanks, @vqvu 

:)
