### ISSUE TITLE
processing in batches

### ISSUE THREAD

**Issue by benjaminhon** [caolan/highland#474]
Hi i can't seem to find a way to process data in batches, here is what i mean

someTimStream
.batchWithTimeOrCount 1000, Infinity
(here i want to accumulate batches that came in the last second and process them array by array)

i tried .toArray()
But this waits for the whole stream to end. What i want is to process each bath as an array.

Is there a good way to do this? thanks

**Comment by vqvu** [comment]
I'm not sure what your question is. Doesn't `batchWithTimeOrCount` emit each batch as an array? What behavior are you looking for exactly?

**Comment by benjaminhon** [comment]
It does, however, i cannot call toArray() while the stream has not ended. only when it ends does toArray() return the batch. I can only do .each() or .map() to process each data in the array.

**Comment by benjaminhon** [comment]
This is what i ended up doing though, not sure if  there is a better way
```
batchWindow = (source) ->

  buffer = []
  batch = []
  batchTrigger = false
  setInterval((->
  batchTrigger = true), 1000)

  source.consume (err, x, push, next) ->
  if err
    # pass errors along the stream and consume next value
    push err
    next()
  else if x is _.nil
    # pass nil (end event) along the stream
    push(null, x)
  else
    # process batch
    if batchTrigger
      # reset trigger
      batchTrigger = false
      # process buffer
      buffer.push batch
      batch = []
      if buffer.length is 4
        push(null, _.chain(buffer).first(3).flatten().value())
        buffer.shift()
    # create batch
    else
      batch.push x
    # next
    next()
```

**Comment by vqvu** [comment]
It looks like what you want is a sliding window of batches of 1-second's worth of data? Is that right?

We don't have a sliding window operator, but there is an outstanding PR for a more general version in #300.

What you have would work too, but I would implement the sliding window separately from the batch since there is already a batching operator.

```javascript
// Sliding window without batchWithTime
window = (source) ->
  buffer = []

  source.consume (err, x, push, next) ->
  if err
    # pass errors along the stream and consume next value
    push err
    next()
  else if x is _.nil
    # pass nil (end event) along the stream
    push(null, x)
  else
    # process batch
    # process buffer
    buffer.push x
    if buffer.length is 4
      push(null, _.chain(buffer).first(3).flatten().value())
      buffer.shift()
    next()

// use like this
stream.batchWithTimeOrCount(1000, Infinity)
    .through(window)
```

**Comment by benjaminhon** [comment]
ah okay, that will work thx
