### ISSUE TITLE
merge / mergeWithLimit inconsistency

### ISSUE THREAD

**Issue by protomouse** [caolan/highland#475]
Consider the following code:

```js
function readFile(name) {
  return _(fs.createReadStream(name));
}

_(['foo', 'bar'])
  .map(readFile)
  .merge()
  .errors(function() {})
  .each(_.log);
```

The intent is to read whatever we can, ignoring any I/O errors, and this works. Calling `mergeWithLimit` instead of `merge` will cause errors to be thrown instead, which I didn't expect.

**Comment by vqvu** [comment]
Should be fixed in #476. Can you confirm?

**Comment by protomouse** [comment]
Yes, I can confirm that it now works. Thanks for the quick response.

**Comment by vqvu** [comment]
v2.7.4 released containing this fix.
