### ISSUE TITLE
Stream created from a promise cannot handle cancellation.

### ISSUE THREAD

**Issue by jaroslav-muller** [caolan/highland#486]
I understand promise cancellation is not standardized, however I use bluebird together with highland and cancellation. Stream created via _(promise) gets blocked when the promise is cancelled.

It's caused by the fact that cancelled promise calls neither success nor error handler, so highland doesn't notice that the promise is finished.

However, it still calls finally handler. The fix seems to be easy, just change this:
```
function promiseStream(promise) {
    return _(function (push) {
        promise.then(function (value) {
                push(null, value);
                return push(null, nil);
            },
            function (err) {
                push(err);
                return push(null, nil);
            });
    });
}
```
to this
```
function promiseStream(promise) {
    return _(function (push) {
        promise.then(function (value) {
                push(null, value);
            },
            function (err) {
                push(err);
            }).finally(function() {
                return push(null, nil);
            });
    });
}

```

**Comment by vqvu** [comment]
`finally` isn't standardized either, so we'd need to gate the new behavior behind a `_.isFunction(promise.finally)` check. Do you mind submitting a PR for this?

**Comment by jaroslav-muller** [comment]
I didn't realize finally is non-standard too.
Anyways, I created the PR. https://github.com/caolan/highland/pull/487
