### ISSUE TITLE
Piping a stream of streams to a node writable?

### ISSUE THREAD

**Issue by peterkhayes** [caolan/highland#499]
I've often used Highland as a batch-processing script tool.  An example use case would be to read a CSV of images, download each image, and write them to files.  However, I'm not sure the right way to do this - I've been using something that seems hacky to me.

``` js
_(urls)
  .map((url) => {
    const source = request(url);
    const dest = fs.createWriteStream(path.join(outputDir, url));
    source.pipe(dest);
    return _(source);
  })
  .parallel(10)
  .done(() => console.log("all finished!"));
```

While this seems to work, it also feels weird because the piping to the destination happens outside of "Highland world".  What I'd really like is something like this:

``` js
_(urls)
  .map((url) => {
    const source = request(url);
    const dest = fs.createWriteStream(path.join(outputDir, url));
    return _(source).pipe(dest);
  })
  .parallel(10)
  .done(() => console.log("all finished!"));
```

But `_(source).pipe(dest)` doesn't return a Highland stream, so I can't use it with `parallel`.  What's the best or most idiomatic way to do this?

**Comment by vqvu** [comment]
You just want to know when the pipe completes, right? If so, you just need to create a new generator stream that pipes to `dest` and and emits `nil` on `finish`.

```javascript
function pipe(src, dest) {
  return _((push, next) => src
    .on('error', push)
    .pipe(dest)
    .on('error', push)
    .on('finish', () => push(null, _.nil)));
}

_(urls)
  .map((url) => {
    const source = request(url);
    const dest = fs.createWriteStream(path.join(outputDir, url));
    return pipe(source, dest);
  })
  .parallel(10)
  .done(() => console.log("all finished!"));
```

**Comment by peterkhayes** [comment]
Thanks, this is useful!  But there's no utility function that does this?

**Comment by vqvu** [comment]
No. Highland doesn't have any special handling for Node `Writable` at all. We will provide utility functions if it helps with interop, but this kind of thing, where you're wrapping the entire `pipe` operation of a different streams library falls out of the realm of interop, in my opinion.
