### ISSUE TITLE
_.of and asyncify

### ISSUE THREAD

**Issue by svozza** [caolan/highland#519]
I find myself reaching for this function a lot, especially in functional pipelines where I currently have to break into a lambda to convert a value into a stream:

```js
const pipeline = hl.compose(hl.flatMap(func3), x => hl([x]), func2, func1);
```

I remember it was actually implemented ages ago in #114 but was part of a larger piece of work to bring Fantasyland compatibility. @quarterto Would you mind if I stole your implementation and tests for a PR? The reason I'm raising this issue is because @megawac suggestion, if I understand it correctly, made me think how trivial it would be to make synchronous functions asynchronous.

```js
const asyncSyncFunc = hl.compose(hl.of, someSyncFunc);
```

**Comment by vqvu** [comment]
> how trivial it would be to make synchronous functions asynchronous.

A proper `asyncify` would need to catch errors, I think, which simply composing `_.of` wouldn't do.

**Comment by svozza** [comment]
Ah good point, guess you'd need to go down the generator route then.

**Comment by vqvu** [comment]
I'm still +1 for `_.of` though. I use it all the time too. Right now, I just have it implemented locally in my code. It would be nice to have direct support in the library.

It would also be nice to have `_.fromError` or extend `_()` to accept `Error`. Sometimes it's useful to create a stream that only emits an error.

**Comment by svozza** [comment]
Yeah, good call on `fromError` I often hand roll that one too. I'm leaning towards an explicit function rather than rolling it into the constructor but I'm open to persuasion.

**Comment by vqvu** [comment]
I prefer the explicit function too.

**Comment by svozza** [comment]
Cool. I'll do that then.
