### ISSUE TITLE
examples with doubled are wrong

### ISSUE THREAD

**Issue by ajoslin103** [caolan/highland#526]
There are a few places in the docs where this snippet is referenced:
```
var doubled = _([1,2,3,4]).map(function (x) {
    return x * 2;
});
```

when this is run, doubled is a highland stream object -- not an array of doubled values

perhaps this is a holdover from an earlier version, but what change will make this work?

is there a syntax where this does work, and doubled == [2,4,6,8] ??

**Comment by vqvu** [comment]
`doubled` has never equaled an array. All Highland transforms return a Highland stream object. If you need an array, you need to use `toArray` and access the callback parameter. So this will work:

```javascript
_([1,2,3,4]).map(function (x) {
    return x * 2;
}).toArray(function (doubled) {
    assert.deepEqual(doubled, [2, 4, 6, 8]);
});
```

The docs should not suggest that `map` returns an array. Can you point to the confusing part of the docs? I see that snippet being used two times, but neither uses say that the result is an array.

**Comment by ajoslin103** [comment]
I think the confusion [for me] came in with the many comments that follow examples 

// => [ <some array contents> ]

This told me [as a newbie] that the return is an array, at least that's how I read it (as a fragment of ES6)

I am no longer thinking in that way & am coming to grips with having to pass a callback to get my results as there seems no other way.

Thanks for a great library!

**Comment by vqvu** [comment]
Ah, I see. I agree that is confusing. Most of the documentation won't use the brackets, which is less confusing. For example, `otherwise` says

```javascript
_([1,2,3]).otherwise(['foo'])  // => 1, 2, 3
```

to mean, "a Highland stream that will emit the elements `1`, `2`, and `3` in that order".j

We should standardize the rest of docs. See #527.
