### ISSUE TITLE
Standardize the way we show stream values in the docs.

### ISSUE THREAD

**Issue by vqvu** [caolan/highland#527]
Standardize the `// => ` syntax in examples when showing what the output of a stream should be. Specifically, we should not wrap the values in square brackets. It looks like an array and is confusing for newbies (see https://github.com/caolan/highland/issues/526#issuecomment-241555193).

It should be
```javascript
_([1, 2, 3, 4]) // => 1, 2, 3, 4
```

and not

```javascript
_([1, 2, 3, 4]) // => [1, 2, 3, 4]
```

The docs for the following transforms does not follow this convention.
- http://highlandjs.org/#transduce
- http://highlandjs.org/#zipAll
- http://highlandjs.org/#zipAll0
- The Arrays section says this. It should have commas for consistency.

  ```javascript
  _.map(doubled, [1, 2, 3, 4])  // => 2 4 6 8
  ```

**Comment by lpww** [comment]
@vqvu I'm looking into this but I have a couple of questions. 

1. The code in the repo (index.html) appears to be different to what is found at highlandjs.org. Some of the comments that I see in your links are missing completely from index.html in the repo?

2. zipAll and zipAll0 are dealing with nested streams. There needs to be some way to indicate that streams are nested. It's not easy to do this in an obvious way when the other stream examples are not wrapped at all. Any preference here? I would suggest something like this to show a stream containing 2 streams: `=> |1, 2, 3|, |4, 5, 6|`

**Comment by vqvu** [comment]
First of all, thanks for taking the time to look at this! To answer your questions:

1. The docs are generated from `docs/templates/base.html` and the doc comments in `lib/index.js`. The latter is formatted in markdown above the block of tags and in an implicit code block below it. The `index.html` file is just a snapshot of the last time I built the docs. It doesn't really have much purpose. Also, the `master` branch contains WIP code for the new 3.x version. You should start at the 2.x branch, as that's still the branch that gets published to the website. I'll merge your work over to the `master` branch as needed.

2. `zipAll` and `zipAll0` take as input nested streams, but they output streams of arrays, so I don't think we have to worry about depicting a stream containing other streams. It's just the outer brackets that are problematic. The inner ones are correct.

**Comment by lpww** [comment]
Legend. Thanks, Victor! Look out for my pr
