### ISSUE TITLE
Splitby method

### ISSUE THREAD

**Issue by carlskii** [caolan/highland#540]
I have a large file that I need to read like this:

```
-----BEGIN DATA-----
MIIEzDCCArSgAwIBAgIVCugKYzMN5ra8zPWxYE8pUU9SxjYSMA0GCSqGSIb3DQEB
CwUAMHAxCzAJBgNVBAYTAkdCMRUwEwYDVQQIDAxXYXJ3aWNrc2hpcmUxEDAOBgNV
BAcMB1dhcndpY2sxEDAOBgNVBAoMB0VudHJ1c3QxETAPBgNVBAsMCFBLSSBURUFN
-----END DATA-----
-----BEGIN DATA-----
MIIETzCCAjegAwIBAgIVBShP2Mx74DZEyNKwYZZPGntRmSWnMA0GCSqGSIb3DQEB
DQUAMHIxCzAJBgNVBAYTAkdCMRUwEwYDVQQIDAxXYXJ3aWNrc2hpcmUxEDAOBgNV
BAcMB1dhcndpY2sxDDAKBgNVBAoMA0lCTTERMA8GA1UECwwIUEtJIFRFQU0xGTAX
5/62
-----END DATA-----
```

I need to get the chunks between the begin and end delimiters. 

However, I'm trying to read the file using `const data = _(["myfile"]).map(readFile).parallel(4);` 

What is meant by readFile ? 

Could you please provide an example of how to read the file and use the `splitby` method

**Comment by carlskii** [comment]
OK so I fixed the `readFile` issue.

```
const readFile = _.wrapCallback(fs.readFile);
stream = _(files).map(readFile).parallel(2);

const blob = _(stream).splitBy('-----BEGIN DATA-----')
```

No that I have a stream, how do I get my data?

**Comment by vqvu** [comment]
You can get at your data by using one of the [Consumption methods](http://highlandjs.org/#Consumption). Usually `each`, `toArray`, or `pipe`. What method you should use depends on what you're trying to do with the data.

For example,

```javascript
readFile('myFile')                    // Reads whole file into memory.
    .splitBy('-----BEGIN DATA-----')  // Splits data
    .filter(chunk => chunk !== '')    // Filters out the initial empty line.
    .each(data => console.log(data)); // Consumes your data. Nothing happens until this call.
```

This should print

```
MIIEzDCCArSgAwIBAgIVCugKYzMN5ra8zPWxYE8pUU9SxjYSMA0GCSqGSIb3DQEB
CwUAMHAxCzAJBgNVBAYTAkdCMRUwEwYDVQQIDAxXYXJ3aWNrc2hpcmUxEDAOBgNV
BAcMB1dhcndpY2sxEDAOBgNVBAoMB0VudHJ1c3QxETAPBgNVBAsMCFBLSSBURUFN
-----END DATA-----
```
then
```
MIIETzCCAjegAwIBAgIVBShP2Mx74DZEyNKwYZZPGntRmSWnMA0GCSqGSIb3DQEB
DQUAMHIxCzAJBgNVBAYTAkdCMRUwEwYDVQQIDAxXYXJ3aWNrc2hpcmUxEDAOBgNV
BAcMB1dhcndpY2sxDDAKBgNVBAoMA0lCTTERMA8GA1UECwwIUEtJIFRFQU0xGTAX
5/62
-----END DATA-----
```

A few notes:

1. You don't need to constantly re-wrap streams. All Highland transforms (e.g., `map`, `parallel`) return Highland streams to support chaining. `_(stream)` is a nop if `stream` is already a Highland stream.
2. If you only have a single file, `parallel` does nothing. You can just do `stream = readFile('myfile')` or even better `stream = _(fs.createReadStream('myfile'))`. The latter doesn't require you to read the entire file into memory.

**Comment by carlskii** [comment]
Great thanks - this works OK great except that the blank lines don't seem to be stripped. 

My output looks like this:

```
3L3hT8lVUn6d2U6cMHB6fXWiYvSxXFNeSHU1jjUUUWdq4yFFvLxpG06gCynKLFEH
5/gslltD/wa1jddwgESQiYwYqZyYdeAIk4QXlHRgr5aqF6g2GoBl9vPIPSiV7F8J
xI5vn52rVwBirlubmf7MB/ROscxymneZF9xWT5NvtF4=



MIIETzCCAjegAwIBAgIVBShP2Mx74DZEyNKwYZZPGntRmSWnMA0GCSqGSIb3DQEB
DQUAMHIxCzAJBgNVBAYTAkdCMRUwEwYDVQQIDAxXYXJ3aWNrc2hpcmUxEDAOBgNV
BAcMB1dhcndpY2sxDDAKBgNVBAoMA0lCTTERMA8GA1UECwwIUEtJIFRFQU0xGTA
````

**Comment by vqvu** [comment]
Are those blank lines where the begin and end tags used to be? You probably need to split by `'-----BEGIN DATA-----\n'` instead then.

**Comment by carlskii** [comment]
Arh yes that did it thanks.
