### ISSUE TITLE
Better use of npm tags

### ISSUE THREAD

**Issue by julien-f** [caolan/highland#541]
You should publish the current stable version with `latest` tag (which is the default) and the beta version with `next` tag (`npm publish --tag next`).

Otherwise, users will install the latest published version which may be the beta without knowing:

```
$ npm i -S highland
highland@3.0.0.0-beta.3
```

**Comment by vqvu** [comment]
So *that's* how you do it. I always thought npm just serves up the latest release by default.

Thanks for the pointer! I think I've fixed it.

```
$ npm dist-tag ls highland
latest: 2.10.0
next: 3.0.0-beta.3
```
