### ISSUE TITLE
Get Last Value in Error Handler

### ISSUE THREAD

**Issue by jayzawrotny** [caolan/highland#575]
Let's say you have code along the following:

```js
_.of(state)
  .through(exports.buildProcess)
  .handleErrors(function (err, push) {
     console.error(err.stack || err.message || err);
     // nonfunctional code
     let state = this.stream.latest();
     updateBuildStatusInDB(state.id, 'error');
     // end nonfunctional code
     push(err);
  });
```
Is there a clean way from inside the error handler to get the last value that was pushed to get the latest state? If not what would be recommended?

**Comment by vqvu** [comment]
Highland doesn't remember old values for you. You'll have to do it yourself. You can use `tap`to do this. 

```javascript
function handleErrors(f) {
  let oldState = null;
  return (stream) => stream
    .tap(state => oldState = state)
    .errors((err, push) => f(err, oldState, push));
}
```

Alternatively, if you somehow have a reference to the latest state when the error is thrown, you can also attach it to the error message.

**Comment by jayzawrotny** [comment]
Ah that makes sense. Thanks again!
