### ISSUE TITLE
Counting lines in large files

### ISSUE THREAD

**Issue by moose56** [caolan/highland#629]
Hi,

I am trying to familiarise myself with using Highland by playing with very large text files.

One toy example I am trying to make is to count the lines in a collection of files and output the total.

Starting with the following code:
```javascript
let total = 0;

_(sourceFiles /* array of paths */)
    .map(fs.createReadStream)
    .flatMap(nodeStream => {
        return _(nodeStream)
            .split()
            //something goes here
    })
    //output here;
```
As they are large files I cannot use toArray and read in the whole thing so I think I need to write a custom consume function, but I cannot figure out the format for this.

Any pointers gratefully received.

**Comment by vqvu** [comment]
You can use [reduce](http://highlandjs.org/#reduce) to count the number of lines.

```javascript
_(sourceFiles)
    .map(fs.createReadStream)
    .flatMap(nodeStream => _(nodeStream)
        .split()
        .reduce(0, (total, line) => total + 1))
```

This will give you a stream that counts the number of lines for each file. If you want the total number of line for *all* files, you'd need to do the reduce again after the `flatMap`.

```javascript
_(sourceFiles)
    .map(fs.createReadStream)
    .flatMap(nodeStream => _(nodeStream)
        .split()
        .reduce(0, (total, line) => total + 1))
    .reduce(0, (total, count) => total + count)
```

You can get at the result by using any of the [Consumption methods](http://highlandjs.org/#Consumption). In this case, `each` or `toCallback` would probably make the most sense.

```javascript
_(sourceFiles)
    .flatMap(fileName => _(fs.createReadStream(fileName))
        .split()
        .reduce(0, (total, line) => total + 1))
    .reduce(0, (total, count) => total + count)
    .each(total => console.log(`Total count is ${total} lines.`))
```

**Comment by moose56** [comment]
Thank you, that is really helpful and a nice simple solution.
