### ISSUE TITLE
Can't collect from "unbounded" EventEmitter (Node exits)

### ISSUE THREAD

**Issue by zommerfelds** [caolan/highland#631]
Hi, I think that the documentation could be clearer about this and/or it could be a nice feature:

When I try to collect and get the value of a Highland stream based on an EventEmitter, Node simply exits instead of giving me all the values when I get an "end" event.

```
const _ = require('highland');
const events = require('events');

const threeRingsEmitter = new events.EventEmitter();
(function ring(remaining) {
  setTimeout(() => {
    threeRingsEmitter.emit('ring', remaining);
    if (remaining-- > 1) ring(remaining);
    else threeRingsEmitter.emit('end');
  }, 1000);
})(3);

// version 1: prints all 3 rings
// _('ring', threeRingsEmitter)
//  .each(console.log);

// version 2: never prints anything
_('ring', threeRingsEmitter)
  .toArray((a) => console.log('array:', a));

```

Same problem with `collect().toPromise()`: it never resolves.

Is there a way to tell Highland which event is the end of the stream? I think that many EventEmitters on npm support such an event and it would be nice to have it available on Highland.

I know that collecting a stream into a variable might not always make sense, but if I do a filter/group operation I might be able to make reasonable assumptions about memory consumption and a collect would be useful in this case.

If this seems of interest I can potentially look into creating a pull request.

**Comment by vqvu** [comment]
I don't know of any built-in way to work with EventEmitters that end, but it's not that difficult to do manually

```javascript
_((push, next) => {
  threeRingsEmitter.on('ring', (x) => push(null, x))
    .on('end', () => push(null, _.nil));
})
.toArray((a) => console.log('array: ', a);
```

We can add some sort of support in Highland to specify a custom 'end' event, but I'm not too keen on overloading the current constructor even more. It's already complicated enough as it is.

**Comment by zommerfelds** [comment]
@vqvu: thanks for the quick answer. That makes sense. I'm not actually sure if it is common to use the `end` event to signal the end of messages in an EventEmitter, but it doesn't seem to be part of the API. I might have confused `event.EventEmitter` with `stream.Readable` because [a library](https://github.com/nice-registry/all-the-packages/blob/master/index.js) uses EventEmitter but should really be using a Readable stream (because `end` is a part of the standard API).

It could still be useful to have a constructor that supports an end event, event though it's a minor feature. Not sure if this is too radical, but we could have something like:
```
_.fromEventEmitter(eventEmitter, dataEvent, endEvent)
```
instead of overloading the constructor.

It's your call whether it fits here or not :)

**Comment by vqvu** [comment]
Let's not do it. Your `fromEventEmitter` idea is good, but I don't think it belongs unless there's a lot of hidden demand for it that I haven't seen.

Plus, `EventEmitters` don't work that well with Highland anyway, because it doesn't support backpressure. It's definitely better to use an (objectMode) `Readable` if you can.
