### ISSUE TITLE
3.0 changes to fork()

### ISSUE THREAD

**Issue by pavel** [caolan/highland#633]
In [CHANGELOG.md](https://github.com/caolan/highland/blob/dd018bf9502e182b0cfa3531b00c3b699b36d4e9/CHANGELOG.md) I've spotted a change in 3.0, which states:
> `fork` - It is no longer possible to call fork after a call to consume. Attempting to do so will result in an error.

This change eliminates a certain stream structure which can be depicted as:

![stream-structure](https://user-images.githubusercontent.com/5321105/28359980-03fc4f14-6c42-11e7-8c03-4e0fba71fdc3.png)

This structure can be used to take data and "preprocess" it, then split the data based on certain conditions to process individually.
What can be done in version 3.0 to create the same (or similar) stream structure?

**Comment by vqvu** [comment]
That still works. What no longer works is this corner case

```javascript
const stream = head.consume(consumer1).consume(consumer2);
stream.take(1); // Stream is consumed.
stream.fork();  // This will fail.
```

The following still works

```javascript
stream.fork().filter(filter1);
stream.fork().filter(filter2);
```

That entry means you can't call `fork` after a `consume` on the same stream. Each call to `consume` creates a new stream, even though it might not look like it.

**Comment by vqvu** [comment]
I've updated the changelog to add a code example that hopefully illustrates the intent of that entry better.

**Comment by pavel** [comment]
Now I see the difference. Thanks!
