### ISSUE TITLE
Can fork() after consume() in 3.0.0-beta.5

### ISSUE THREAD

**Issue by pavel** [caolan/highland#634]
As stated In [CHANGELOG.md](https://github.com/caolan/highland/blob/dd018bf9502e182b0cfa3531b00c3b699b36d4e9/CHANGELOG.md) for 3.0:
> `fork` - It is no longer possible to call fork after a call to consume. Attempting to do so will result in an error.

But this is still possible in 3.0.0-beta.5.

Demo link: https://jsfiddle.net/L5e94jbp/1/

**Comment by vqvu** [comment]
Yep, it should work. See my comment in #633. Sorry for the confusion.
