### ISSUE TITLE
Issue with AWS SDK

### ISSUE THREAD

**Issue by brunomanzo** [caolan/highland#654]
Hello,

I am trying to use this lib to control some flows where I put some records on AWS Kinesis firehose, but I am getting a weird error inside aws lib. The original function is like this:
```
    firehose.putRecord(params, function(err, data) {
      if (err) {
        console.log(err, err.stack); // an error occurred
      } else console.log(data); // successful response
    });
```

when I do this:
```
  let firehoseWrapper = streamHighland.wrapCallback(firehose.putRecord);
...
.map(mapFirehose)
    .map(firehoseWrapper)
    .series()
    .each(console.log)
```
I get this error:

```
/home/bruno/Dev/consolidate-rri/node_modules/aws-sdk/lib/service.js:499
          return this.makeRequest(method, params, callback);
                      ^

TypeError: this.makeRequest is not a function
```

I tried also not using the wrapper itself:
```
  function firehoseWrapper(rri) {
    console.log(rri);
    // create a new Stream
    return streamHighland(function (push, next) {
      firehose.putRecord(params, function(err, data) {
        push(err, data)
      });
    });
};
```
But got the same error. Any toughs on what I could do?

**Comment by tomwhale** [comment]
You need to bind `firehose` to `this`.

`let firehoseWrapper = streamHighland.wrapCallback(firehose.putRecord.bind(firehose));`

**Comment by svozza** [comment]
From what I remember, the AWS SDK did some weird stuff with `this`, as a workaround I would suggest using the highland constructor and sdk's promise functionality

```js
highland(firehouse.putRecord(params).promise());
```

**Comment by brunomanzo** [comment]
@tomwhale Worked after binding :)!!! Really thx for the super fast response. Closing the issue since it's solved <3
