### ISSUE TITLE
Process groups after `group` call separately and combine again. 

### ISSUE THREAD

**Issue by benyamin-noori** [caolan/highland#680]
The goal is to group items in a stream into multiple groups. Run transformations on those groups separately and then re-combine all the groups into one stream. 

The only call I can use after `group` seems to be `each` and that doesn't pass individual groups to my callback it passes the entire dictionary of grouped objects. Calling `map` won't pass anything to my callback. Example: 

```javascript
const groups = stream.group(func);
groups.map(item => console.log(item)); // prints nothing
groups.each(item => console.log(item)); // instead of item being one of the groups created, it's a dictionary with all the groups included. 
```

**Comment by amsross** [comment]
Until you consume a stream, none of the actions you declare on a stream (ie: `.map(item => console.log(item)`) will be performed.

Try something like this, where you have _only *one*_ variable `groups`, and your calls are _chained_:
```
const groups = _([1, 2, 3, 4])
  .group(x => x > 2 === 0)
  .map(group => (console.log(group), group)) // first [ 1, 2 ], then [ 3, 4 ]

groups.each(item => console.log(item)) // first [ 1, 2 ], then [ 3, 4 ]
```
