### ISSUE TITLE
Lazy Node Readable Streams?

### ISSUE THREAD

**Issue by richardscarrott** [caolan/highland#690]
I've been struggling to nicely compose native Node streams with `pipeline`, `pumpify`, `merge2`, `through2` and the gazillion other npm libs out there, so it's really cool to see `highland` which seems to have a much more cohesive design.

One problem I have in particular with Node streams is they're eager, so calling `pipe` will immediately start reading from the `Readable` stream e.g.

```js
const pipeline = readable.pipe(transform1).pipe(transform2); // Starts reading from `readable` even though it's not yet being piped to a writable.
// ... Later on ...
pipeline.pipe(writable); // Ideally it would start reading now imo.
```

I guess this is because `pipe` doesn't differentiate between a `Duplex` stream and a `Writable` so it just starts reading immediately.

I think it's for this reason that highland has similar behaviour, e.g.

```js
_(readable) // `readable` starts being read immediately
```

I wondered whether it would be possible to have `Readable` streams become lazily evaluated so they're not read until one of the "consumption" methods is called, e.g. `pipe`?

This would allow us to declare sequences like this for example:

```js
   const pipeline1 = _(readable1)
        .map((chunk) => {
            return `::${chunk}::`;
        });

    const pipeline2 = _(readable2)
        .map((chunk) => {
            return `>>${chunk}<<`;
        });

    // Ideally `readable2` would not be read from until `pipeline1` has finished. 
    _([pipeline1, pipeline2])
        .sequence()
        .pipe(writable);
```

I had been using [`merge2`](https://github.com/teambition/merge2) for sequencing which suffered the same problem e.g.

```js
merge(pipeline1, pipeline2).pipe(writable);
```

But on a local fork of `merge2`, I've provided support for lazy evaluation by passing a fn e.g.

```js
merge(() => pipeline1, () => pipeline2).pipe(writable)
```

However I imagine highland could in fact handle this under the hood without the need for a fn to be passed?

**Comment by vqvu** [comment]
I think if you replace `_(readable)` with `_.of(readable).flatMap(_)`, you'll get the lazy behavior you want.

**Comment by richardscarrott** [comment]
@vqvu amazing! I'm already really impressed with Highland, thanks for your help, it's much appreciated 👍
