### ISSUE TITLE
Simple output to file is throwing an error

### ISSUE THREAD

**Issue by khawtf** [caolan/highland#697]
var _ = require('highland');
    var Combinatorics = require('js-combinatorics');
    var fs = require('fs');
    var logger = fs.createWriteStream('log.txt', {
        flags: 'a'
    });

    var pos = Combinatorics .baseN([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 2);
    _(pos).pipe(logger)

It's pretty straightforward but I am always getting this error:

 _The "chunk" argument must be one of type string or Buffer. Received type object_

**Comment by amsross** [comment]
You're trying to pipe a stream of arrays into a writeStream, but you need to give it a stream of string chunks.

Try something like this:
```
_(pos.toArray()).collect().map(JSON.stringify).pipe(logger)
```

**Comment by khawtf** [comment]
@amsross thanks matt that made it work :) was debugging it for an hour 👍 
Now I hit another wall if i change the 2 to a 7 (second parameter of the baseN) it throws a 

Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

isn't a stream exactly to prevent this ?
