### ISSUE TITLE
Website no longer exists

### ISSUE THREAD

**Issue by richardscarrott** [caolan/highland#704]
<img width="1025" alt="Screenshot 2020-06-17 at 13 59 42" src="https://user-images.githubusercontent.com/539309/84901299-309d6280-b0a3-11ea-8136-c517176bf53e.png">

Maybe worth pushing the website to a github page instead if the domain is no longer owned?

**Comment by caolan** [comment]
I've updated the documentation to use the github pages URL directly. I've renewed the domain for another year with a permanent redirect to https://caolan.github.io/highland, but may let it expire after that...

**Comment by jaidetree** [comment]
Thanks @caolan would you be open to transferring it to someone who's willing to maintain it before it expires next year?

**Comment by caolan** [comment]
@eccentric-j I'd keep the github.io domain listed here, but transferring highlandjs.org to a contributor is preferable to letting a squatter grab it, yes.
